ej.RTE.Locale["de-DE"] = {
            bold: "fett",
            italic: "kursiv",
            underline: "unterstreichen",
            strikethrough: "Durchgestrichen",
            superscript: "Überschrift",
            subscript: "Index",
            justifyCenter: "Text-Zentrum",
            justifyLeft: "Ausrichten von Text links",
            justifyRight: "Ausrichten von Text rechts",
            justifyFull: "rechtfertigen",
            fileBrowser: "Datei-Browser",
            unorderedList: "Legen Sie ungeordnete Liste",
            orderedList: "Geordnete Liste einfügen",
            indent: "Einzug",
            outdent: "Einzug verkleinern",
			cut: "schneiden",
			copy: "Kopieren",
			paste: "Paste",
            undo: "lösen",
            redo: "Wiederherstellen",
			upperCase: "Großbuchstaben",
			lowerCase: "Kleinbuchstaben",
            clearAll: "Alles",
            clearFormat: "Klar Format",
            createLink: "Einfügen / Hyperlink Bearbeiten",
			removeLink:"fjern Hyperlink",
			tableProperties: "Tabelleneigenschaften",
			insertTable: "Einfügen",
			deleteTables: "Löschen",
			imageProperties: "Bildeigenschaften",
			openLink: "Verbindung öffnen",
            image: "Bild einfügen",
            video: "Legen Video",
            embedVideo: "Fügen Sie den Embed-Code unten",
            viewHtml: "Blick HTML",
			fontName: "Wählen Sie Schriftfamilie",
			fontSize: "Wählen Sie Schriftgröße",
			fontColor: "Wählen Sie die Farbe",
            format: "Format",
			backgroundColor: "Hintergrundfarbe",
			style: "Styles",
            deleteAlert: "Sind Sie sicher, dass Sie alle Inhalte löschen?",
			copyAlert: "Ihr Browser unterstützt leider keinen direkten Zugriff auf die Zwischenablage. Bitte verwenden Sie die Ctrl + C -Tastatur statt Kopiervorgang Verknüpfung .",
			pasteAlert:"Ihr Browser unterstützt leider keinen direkten Zugriff auf die Zwischenablage. Bitte verwenden Sie die Ctrl + V Tastenkombination statt Einfügen.",
			cutAlert:"Ihr Browser unterstützt leider keinen direkten Zugriff auf die Zwischenablage. Bitte verwenden Sie die Ctrl + X Tastenkombination statt Schneidevorgang.",
            videoError: "Der Textbereich darf nicht leer sein",
            imageWebUrl: "Webadresse",
            imageAltText: "Bildbeschreibung",
            dimensions: "Größe",
            constrainProportions: "Proportionen",
            linkWebUrl: "Webadresse",
            linkText: "Text",
            linkTooltipLabel: "Tooltip",
            html5Support: "Dieses Werkzeug-Symbol nur in HTML5 aktiviert unterstützten Browser",
            linkOpenInNewWindow: "Link in einem neuen Fenster",
            tableColumns: "Spalten",
            tableRows: "Zeilen",
            solid: "solide",
            dashed: "gestippelde",
            dotted: "stippel",
            doubled: "dubbele",
            buttonApply: "toepassen",
            buttonCancel: "annuleren",
            closeIcon: "dicht",
            tableWidth: "Tischbreite",
            tableHeight: "Tischhöhe",
            tableCellSpacing: "Zellenabstand",
            tableCellPadding: "Zellauffüllung",
            tableBorder: "Grenze",
            tableCaption: "Beschriftung",
            tableAlignment: "Ausrichtung",
            dialogUpdate: "Aktualisierung",
            dialogInsert: "einfügen",
            dialogCancel: "stornieren",
            dialogOk: "Ok",
            createTable: "Tabelle erstellen",
            addColumnLeft: "Spalte links hinzufügen",
            addColumnRight: "In Spalte auf der rechten",
            addRowAbove: "Zeile hinzufügen oben",
            addRowBelow: "Zeile hinzufügen unten",
            deleteRow: "Löschen Sie die Zeile",
            deleteColumn: "Löschen Sie die Spalte",
            deleteTable: "Löschen Sie die Tabelle",
			insertTable:"Einfügen",
            customTable: "von benutzerdefinierten Tabelle",
            characters: "Charaktere",
            dialogApply: "anwenden",
            textAlign: "Text ausrichten",
            imageLink: "Bild als Link zu",
            imageBorder: "Bild Rand",
            imageStyle: "Stil",
            editTable: "Tabelle Eigenschaften bearbeiten",
			words: "Wörter",
            general: "allgemein",
            advanced: "fortgeschritten",
            table: "Tisch",
            row: "Reihe",
            column: "Spalte",
            cell: "Zelle",
			maximize:"Maximieren",
		    resize: "Minimieren",
			swatches: "Farbfelder",
			paragraph:"Absatz",
		    quotation:"Zitat",
		    heading1:"Kopf 1",
		    heading2:"Kopf 2",
		    heading3:"Kopf 3",
		    heading4:"Kopf 4",
		    heading5:"Kopf 5",
		    heading6:"Kopf 6",
			disc:"Scheibe",
		    circle:"Kreis",
		    square:"Platz",
		    number:"Anzahl",
		    loweralpha:"Lower Alpha",
		    upperalpha:"Ober Alpha",
		    lowerroman:"Lower Roman",
		    upperroman:"Ober Roman",
		    none:"Keine",
			linkTooltip:"ctrl + Klick Link zu folgen",
			charSpace: "Zeichen (mit Leerzeichen )",
			charNoSpace: "Zeichen (ohne Leerzeichen)",
			wordCount: "Wortzahl",
			right:"Recht",
			left:"links",
			center:"Center",
			FindAndReplace:"Suchen und Ersetzen",
			Find:"Finden",
			MatchCase:"Kleinschreibung",
			WholeWord:"Ganze Welt",	
			ReplaceWith:"Ersetzen mit",		
			Replace:"Ersetzen",
			ReplaceAll:"Alles ersetzen",
			FindErrorMsg:"Konnte den angegebenen Wort gefunden .",
			customFontColor:"Mehr Farben...",
		    customBGColor:"Mehr Farben...",
			TransBGColor:"Transparent",
			w:"W",
		    c:"C"
			
        };

        ej.RTE.Locale["es-ES"] = {
            bold: "audaz",
            italic: "itálico",
            underline: "subrayar",
            strikethrough: "Tachado",
            superscript: "sobrescrito",
            subscript: "subíndice",
            justifyCenter: "Centrar texto",
            justifyLeft: "Alinear texto a la izquierda",
            justifyRight: "Alinear texto a la derecha",
            justifyFull: "justificar",
            fileBrowser: "archivo Browser",
            unorderedList: "Inserte lista desordenada",
            orderedList: "Insertar lista ordenada",
            indent: "muesca",
            solid: "solida",
            dashed: "frauditaj",
            dotted: "punktita",
            doubled: "duobla",
            closeIcon: "Fermi",
            buttonApply: "apliki",
            buttonCancel: "nuligi",
            outdent: "reducir sangría",
			cut: "Cortar",
			copy: "Copia",
			paste: "Pegar",
            undo: "deshacer",
            redo: "rehacer",
			upperCase: "Mayúscula",
			lowerCase: "Minúscula",
            clearAll: "Borrar todo",
            clearFormat: "Claro Formato",
            createLink: "Insertar / Editar hipervínculo",
			removeLink:"quitar hipervínculo",
			tableProperties: "Propiedades de la tabla",
			insertTable: "Insertar",
			deleteTables: "Borrar",
			imageProperties: "Propiedades de la imagen",
			openLink: "Abrir hipervínculo",
            image: "insertar una imagen",
            video: "insertar vídeo",
            embedVideo: "Pegue su código de inserción por debajo de",
            viewHtml: "Ver HTML",			
			fontName: "Seleccione familia de fuentes",
			fontSize: "Seleccione el tamaño del texto",
			fontColor: "Seleccionar el color",
            format: "formato",
			backgroundColor: "Color de fondo",
			style: "estilos",
            deleteAlert: "¿Está seguro que desea borrar todo el contenido?",
			copyAlert: "Su navegador no es compatible con el acceso directo al portapapeles. Utilice el teclado Ctrl + C atajo en lugar de operación de copia .",
			pasteAlert:"Su navegador no es compatible con el acceso directo al portapapeles. Por favor, use la combinación de teclas Ctrl + V en lugar de operación de pegado ",
			cutAlert:"Su navegador no es compatible con el acceso directo al portapapeles. Utilice el Ctrl + X combinación de teclas en lugar de la operación de corte .",
            copyPastAlert: "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.",
            videoError: "El área de texto no puede estar vacío",
            imageWebUrl: "Dirección web",
            imageAltText: "Descripción",
            dimensions: "dimensiones",
            constrainProportions: "Restringir proporciones",
            linkWebUrl: "Dirección web",
            linkText: "texto",
            linkTooltipLabel: "ToolTip",
            html5Support: "Este icono de la herramienta sólo disponible en HTML5 apoyó navegadores",
            linkOpenInNewWindow: "Abrir enlace en una nueva ventana",
            tableColumns: "No. de Columnas",
            tableRows: "Numero de Filas",
            tableWidth: "ancho de la mesa",
            tableHeight: "altura de la mesa",
            tableCellSpacing: "El espaciado",
            tableCellPadding: "Relleno",
            tableBorder: "frontera",
            tableCaption: "subtítulo",
            tableAlignment: "alineación",
            dialogUpdate: "actualización",
            dialogInsert: "insertar",
            dialogCancel: "cancelar",
            dialogOk: "bueno",
            createTable: "Crear una tabla",
            addColumnLeft: "Añadir la columna de la izquierda",
            addColumnRight: "Añadir columna a la derecha",
            addRowAbove: "Añadir fila encima",
            addRowBelow: "Añadir fila abajo",
            deleteRow: "Elimine la fila",
            deleteColumn: "Eliminar la columna",
            deleteTable: "Eliminar la tabla",
			insertTable:"Insertar",
            customTable: "Crear una tabla personalizada",
            characters: "Personajes",
            dialogApply: "aplicar",
            textAlign: "Texto Alinear",
            imageLink: "Imagen como Enlace",
            imageBorder: "Imagen de fronteras",
            imageStyle: "Estilo",
            editTable: "Editar las propiedades de la tabla",
			words: "palabras",
            general: "corriente",
            advanced: "avanzada",
            table: "tabla",
            row: "fila",
            column: "columna",
            cell: "célula",
			maximize:"Maximizar",
		    resize: "Minimizar",
			swatches: "Muestras",
			paragraph:"acápite",
		    quotation:"cita",
		    heading1:"título 1",
		    heading2:"título 2",
		    heading3:"título 3",
		    heading4:"título 4",
		    heading5:"título 5",
		    heading6:"título 6",
			disc:"Disco",
		    circle:"Círculo",
		    square:"Cuadrado",
		    number:"Número",
		    loweralpha:"Baja Alfa",
		    upperalpha:"Alta Alfa",
		    lowerroman:"Baja romano",
		    upperroman:"Alta romano",
		    none:"Ninguna",
			linkTooltip:"ctrl + clic para seguir el enlace",
			charSpace: "Caracteres (con espacios)",
			charNoSpace: "Caracteres (sin espacios)",
			wordCount: "El recuento de palabras",
			right:"derecho",
			left:"izquierda",
			center:"centrar",						
			FindAndReplace:"Buscar y reemplazar",
			Find:"Encontrar",
			MatchCase:"Coincidencia",
			WholeWord:"Palabra completa",	
			ReplaceWith:"Remplazar con",		
			Replace:"Reemplazar",
			ReplaceAll:"Reemplaza todo",
			FindErrorMsg:"No se pudo encontrar la palabra especificada .",
			customFontColor:"Mas colores...",
            customBGColor:"Mas colores...",
            TransBGColor:"transparente",
            w:"W",
            c:"C"
        };

                     $(function () {
                         $("#sampleProperties").ejPropertiesPanel();
                     });

            
            function onChange(args) {
                $("#LayoutSection_ControlsSection_rteSample").ejRTE("model.locale", args.value);
            }