<%@ Page Title="Spreadsheet-Localization-ASP.NET-SYNCFUSION"   Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" MetaDescription="This demo shows the localization of the Syncfusion ASP.NET Web Spreadsheet control" CodeBehind="Localization.aspx.cs" Inherits="WebSampleBrowser.SpreadsheetASP.Localization" %>

<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="HeadSection">
    <script src="../Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <link href="../Content/Spreadsheet/SpreadsheetStyles.css" rel="stylesheet" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="SampleHeading" runat="server">
    <span class="sampleName">Spreadsheet / Localization</span>
</asp:Content>

<asp:Content ID="ControlContent" runat="server" ContentPlaceHolderID="ControlsSection">
    <div>
        <ej:Spreadsheet ID="FlatSpreadsheet" AllowFormulaBar="false" ShowRibbon="false" AllowSearching="false" AllowFiltering="false"
            Locale="es-ES"  AllowHyperlink="false" runat="server">
            <ClientSideEvents LoadComplete="loadComplete" />
            <ScrollSettings Height="450" />
            <Sheets>
                <ej:Sheet>
                    <RangeSettings>
                        <ej:RangeSetting StartCell="A3" />
                    </RangeSettings>
                </ej:Sheet>
            </Sheets>
        </ej:Spreadsheet>
    </div>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ScriptSection" runat="server">
    <script type="text/javascript">

        function loadComplete(args) {
            this.setWidthToColumns([133, 135, 133, 218, 181, 145]);
            this.XLEdit.updateValue("D1", "SPANISH CULTURE");
            this.XLFormat.format({ "style": { "font-weight": "bold", "text-align": "center" } }, "D1");
            this.XLFormat.format({ "style": { "font-weight": "bold", "vertical-align": "middle", "text-align": "center" } }, "A1");
            this.XLFormat.format({ "style": { "font-weight": "bold" } }, "A3:F3");
            this.performSelection("A3");
        }

        ej.Spreadsheet.Locale["es-ES"] = {
            Cut: "Cortar",
        Copy: "Copia",
        FormatPainter: "Copiar formato",
        Paste: "Pegar",
        PasteValues: "Sólo pegar valores",
        PasteSpecial: "Pegar",
        Filter: "Filtrar",
        FilterContent: "Activar el filtrado de las celdas seleccionadas.",
        FilterSelected: "Filtrar por el valor de la celda seleccionada",
        Sort: "Ordenar",
        Clear: "Claro",
        ClearContent: "Eliminar todo en la célula, o eliminar sólo los de formato, contenidos, comentarios o hipervínculos.",
        ClearFilter: "Borrar filtro",
        ClearFilterContent: "Limpiar el filtro y ordenar el estado de la gama actual de datos.",
        SortAtoZ: "Ordenar de A a Z",
        SortAtoZContent: "Los más bajos.",
        SortZtoA: "Ordenar de Z a A",
        SortZtoAContent: "De mayor a menor.",
        SortSmallesttoLargest: "Ordenar de menor a mayor",
        SortLargesttoSmallest: "Ordenar de mayor a menor",
        SortOldesttoNewest: "Ordenar antiguo a más reciente",
        SortNewesttoOldest: "Ordenar reciente al más antiguo",
        Insert: "Insertar",
        InsertTitle: "Las células de inserción",
        InsertContent: "Añadir nuevas celdas, filas o columnas a su libro <br /> <br /> Para su información:. Para insertar varias filas o columnas a la vez, seleccionar varias filas o columnas de la hoja, y haga clic en Insertar.",
        InsertSBContent: "Añadir celdas, filas, columnas u hojas de su libro.",
        Delete: "Borrar",
        DeleteTitle: "eliminar celdas",
        DeleteContent: "Eliminar celdas, filas, columnas u hojas de su libro de trabajo <br /> <br /> Para su información:. Para eliminar varias filas o columnas a la vez, seleccionar varias filas o columnas de la hoja, y haga clic en Eliminar.",
        FindSelectTitle: "Buscar y seleccionar",
        FindSelectContent: "Haga clic para ver opciones para buscar texto en el documento.",
        CalculationOptions: "Opciones de cálculo",
        CalcOptTitle: "Opciones de cálculo",
        CalcOptContent: "Elige fórmulas para calcular de forma automática o manualmente. <br/> Si se realiza un cambio que afecta a un valor, hoja de cálculo volverá a calcular automáticamente.",
        CalculateSheet: "Calcula Hoja",
        CalculateNow: "calcular Ahora",
        CalculateNowContent: "Calcula el libro completo ahora. <br/> Sólo es necesario usar esta opción si el cálculo automático está desactivado.",
        CalculateSheetContent: "Calcular la hoja activa ahora. <br/> Sólo es necesario usar esta opción si el cálculo automático está desactivado.",
        Title: "Hoja de cálculo",
        Ok: "DE ACUERDO",
        Cancel: "Cancelar",
        Alert: "No podríamos hacer esto para el rango de celdas seleccionado. Seleccionar una sola celda dentro de un rango de datos y vuelva a intentarlo.",
        HeaderAlert: "El comando no pudo completarse debido a que está intentando filtrar con el cabezal del filtro. Seleccionar una sola celda en el rango del filtro y a intentar el mandato.",
        FlashFillAlert: "Todos los datos próximos a la selección fue verificada y no hubo un patrón para el relleno de valores.",
        Formatcells: "Formato de celdas",
        FontFamily: "Fuente",
        FFContent: "Elegir un nuevo tipo de letra para el texto.",
        FontSize: "Tamaño de fuente",
        FSContent: "Cambiar el tamaño de su texto.",
        IncreaseFontSize: "Aumentar tamaño de fuente",
        IFSContent: "Haga su texto un poco más grande.",
        DecreaseFontSize: "Disminuir fuente",
        DFSContent: "Haga su texto un poco más pequeño.",
        Bold: "Negrita",
        Italic: "Itálico",
        Underline: "Subrayar",
        Linethrough: "A través de la línea",
        FillColor: "Color de relleno",
        FontColor: "Color de fuente",
        TopAlign: "Alinear arriba",
        TopAlignContent: "Alinear el texto a la parte superior.",
        MiddleAlign: "Alinear Medio",
        MiddleAlignContent: "Alinear el texto de modo que quede centrado entre la parte superior e inferior de la celda.",
        BottomAlign: "Alinear abajo",
        BottomAlignContent: "Alinear el texto a la parte inferior.",
        WrapText: "Ajustar el texto",
        WrapTextContent: "Ajustar el texto extra larga en varias líneas para que pueda ver todo.",
        AlignLeft: "Alinear a la izquierda",
        AlignLeftContent: "Alinear su contenido a la izquierda.",
        AlignCenter: "Centrar",
        AlignCenterContent: "Centro de su contenido.",
        AlignRight: "alinear a la derecha",
        AlignRightContent: "Alinear su contenido a la derecha.",
        Undo: "Deshacer",
        Redo: "Rehacer",
        NumberFormat: "Formato numérico",
        NumberFormatContent: "Elija el formato de sus células, como porcentaje, moneda, fecha u hora.",
        AccountingStyle: "Estilo de Contabilidad",
        AccountingStyleContent: "Formato que el formato de número de contabilidad en dólares.",
        PercentageStyle: "Estilo ciento",
        PercentageStyleContent: "Formato como un porcentaje.",
        CommaStyle: "Estilo millares",
        CommaStyleContent: "Formato sin separador de miles.",
        IncreaseDecimal: "aumentar decimales",
        IncreaseDecimalContent: "Ver más lugares decimales para un valor más preciso.",
        DecreaseDecimal: "disminuir decimales",
        DecreaseDecimalContent: "Mostrar menos cifras decimales.",
        AutoSum: "Autosuma",
        AutoSumTitle: "Suma",
        AutoSumContent: "Añadir automáticamente un cálculo rápido de la hoja de cálculo, tales como suma o promedio.",
        Fill: "Llenar",
        ExportXL: "Sobresalir",
        ExportCsv: "CSV",
        SaveXml: "Guardar XML",
        BackgroundColor: "Color de relleno",
        BGContent: "Colorear el fondo de las células para hacer que destaquen.",
        ColorContent: "Cambiar el color de su texto.",
        Border: "Frontera",
        BorderContent: "Aplicar bordes a las celdas seleccionadas.",
        BottomBorder: "Borde inferior",
        TopBorder: "Border,",
        LeftBorder: "Borde izquierdo",
        RightBorder: "Borde derecho",
        OutsideBorder: "fronteras exteriores",
        NoBorder: "Sin bordes",
        AllBorder: "todas las fronteras",
        ThickBoxBorder: "Gruesa borde de cuadro",
        ThickBottomBorder: "Borde inferior grueso",
        TopandThickBottomBorder: "Superior e inferior grueso de la frontera",
        DrawBorderGrid: "Dibujar borde de cuadrícula",
        DrawBorder: "dibujar borde",
        TopandBottomBorder: "Superior e inferior de la frontera",
        BorderColor: "Color de linea",
        BorderStyle: "Estilo de línea",
        Number: "Número se utiliza para la visualización general de números. Moneda y oferta contabilidad especializada para dar formato a un valor monetario.",
        General: "Formato de celdas generales no tienen formato de número específico.",
        Currency: "Los formatos de moneda se utilizan para los valores monetarios generales. Utilice formatos de Contabilidad para alinear los puntos decimales en una columna.",
        Accounting: "formatos de contabilidad se alinean los símbolos de moneda y puntos decimales en una columna.",
        Text: "Formato de celdas de texto se tratan como texto, incluso cuando un número está en la célula. La célula se muestra exactamente como introducido.",
        Percentage: "formatos porcentuales multiplican el valor de la celda por 100 y muestra el resultado con un símbolo de porcentaje.",
        CustomMessage: "Escriba el código de formato de número, usando uno de código existente como punto de partida.",
        Fraction: " ",
        Scientific: " ",
        Type: "Tipo:",
        CustomFormatAlert: "Introduzca un formato válido",
        Date: "Formatos de fecha muestran números de serie de fecha y hora como valores de fecha.",
        Time: "Tiempo formatos de fecha de visualización y números de serie de tiempo como valores de fecha.",
        File: "ARCHIVO",
        New: "Nuevo",
        Open: "Abierto",
        SaveAs: "Guardar como",
        Print: "Impresión",
        PrintContent: "Imprimir la hoja actual.",
        PrintSheet: "Imprimir",
        PrintSelected: "De impresión, seleccione",
        PrintSelectedContent: "Seleccionar un área en la hoja que desea imprimir.",
        HighlightVal: "Formato de datos no válidos",
        ClearVal: "claro Validación",
        Validation: "Validación",
        DataValidation: "Validación de datos",
        DVContent: "Escoger de una lista de reglas para limitar el tipo de datos que se pueden introducir en una célula.",
        A4: "A4",
        A3: "A3",
        Letter: "Carta",
        PageSize: "Tamaño de página",
        PageSizeContent: "Elija un tamaño de página para el documento.",
        FormatCells: "Formato de celdas",
        ConditionalFormat: "Formato condicional",
        CFContent: "Fácilmente detectar tendencias y patrones en sus datos usando los colores para resaltar visualmente los valores importantes.",
        And: "y",
        With: "con",
        GTTitle: "Mas grande que",
        GTContent: "Formato de celdas que son mayores que:",
        LTTitle: "Menos que",
        LTContent: "Formato de celdas que son menos de:",
        BWTitle: "Entre",
        BWContent: "Formato de celdas que se encuentran entre:",
        EQTitle: "Igual a",
        EQContent: "Formato de celdas que se van a EQUAL:",
        DateTitle: "Una fecha que se sitúa",
        DateContent: "Formato de celdas que contienen una fecha:",
        ContainsTitle: "Texto que contiene",
        ContainsContent: "Formato de celdas que contienen el texto:",
        GreaterThan: "Mas grande que",
        LessThan: "Menos que",
        Between: "Entre",
        EqualTo: "Igual a",
        TextthatContains: "El texto que contiene",
        DateOccurring: "Una fecha que se sitúa",
        ClearRules: "Reglas claras",
        ClearRulesfromSelected: "Reglas claras de las celdas seleccionadas",
        ClearRulesfromEntireSheets: "Reglas claras de hoja entera",
        CellStyles: "Estilos de celda",
        CellStylesContent: "Un estilo colorido es una gran manera de hacer que los datos importantes se destacan en la hoja.",
        CellStyleHeaderText: "Bueno, malo y neutral / títulos y encabezamientos Estilos de celda / temáticos",
        Custom: "Escriba el código de formato de número, usando uno de los códigos existentes como punto de partida.",
        CellStyleGBN: "Normal / Bad / Buena / Neutro",
        CellStyleTH: "Rúbrica 4 / Título",
        CellsStyleTCS: "20% - Accent1 / 20% - accent2 / 20% - Accent3 / 20% - Accent4 / 60% - Accent1 / 60% - accent2 / 60% - Accent3 / 60% - Accent4 / Accent1 / accent2 / Accent3 / Accent4",
        Style: "Estilo",
        FormatAsTable: "Como formato de tabla",
        FormatasTable: "Formato que la tabla",
        FATContent: "convertir rápidamente un rango de celdas a una tabla con su propio estilo.",
        FATHeaderText: "Light / Medium / Dark",
        FATNameDlgText: "Nombre de la tabla: / Mi tabla tiene encabezados",
        InvalidReference: "La escala que ha especificado no es válido",
        ResizeAlert: "El rango especificado no es válido. La parte superior de la mesa debe permanecer en la misma fila, y la tabla resultante deberá coincidir con la tabla original. Especificar un rango válido.",
        RangeNotCreated: "El aumento de la fila más allá del máximo número de hojas fila está restringido en formato como tabla.",
        ResizeRestrictAlert: "Aumento o disminución del número de columnas y la disminución de la cantidad de filas está restringida en formato como tabla.",
        FATResizeTableText: "Introducir un nuevo rango de datos para la tabla:",
        FATReizeTableNote: "Nota: Los encabezados deben permanecer en la misma fila y el rango de la tabla resultante se deben superponer el rango tabla original.",
        FormatAsTableAlert: "No se puede crear una tabla con una sola fila. Una tabla debe tener al menos dos filas, una para el encabezado de la tabla, y una para datos",
        FormatAsTableTitle: "Luz 1 / Luz 2 / Luz 3 / Luz 4 / luz 5/6 de luz / luz 7 / Luz 8 / Luz 9 / luz 10 / luz 11 / luz 12 / Medio 1 / Media 2 / Medio 3 / Medio 4 / Medio 5 / Medium 6 / Medium 7 / Medio 8/1 oscuro / Dark 2/3 oscuro / Dark 4",
        NewTableStyle: "Nuevo estilo de tabla",
        ResizeTable: "Cambiar el tamaño de la tabla",
        ResizeTableContent: "Cambiar el tamaño de esta tabla añadiendo o eliminando filas y columnas.",
        ConvertToRange: "Convertir en rango",
        ConvertToRangeContent: "Convertir esta tabla en un rango normal de las células.",
        ConverToRangeAlert: "¿Quieres convertir la tabla a un rango normal?",
        TableID: "ID de tabla:",
        Table: "Mesa",
        TableContent: "Crear una tabla para organizar y analizar datos relacionados.",
        TableStyleOptions: "Primera Columna / Última columna / fila Total / botón de filtro",
        Format: "Formato",
        NameManager: "nombre del manager",
        NameManagerContent: "Crear, editar, eliminar y encontrar todos los nombres utilizados en el libro. <br /> <br /> Los nombres pueden ser utilizados en fórmulas como sustitutos de las referencias de celda.",
        DefinedNames: "Nombres definidos",
        DefineName: "definir nombre",
        DefineNameContent: "Definir y aplicar nombres.",
        UseInFormula: "En la Fórmula utilizar",
        UseInFormulaContent: "Elija un nombre usado en este libro y la inserta en la fórmula actual.",
        RefersTo: "Se refiere a",
        Name: "Nombre",
        Scope: "Alcance",
        NMNameAlert: "El nombre que ha introducido no es valid./Reason para esto pueden incluir: / el nombre no comienza con una letra o un guión bajo / El nombre contiene un espacio u otros caracteres no válidos / Los conflictos de nombres con una hoja de cálculo integrada en el nombre o el nombre de otro objeto en el libro, no se utiliza completamente //",
        NMUniqueNameAlert: "El nombre introducido ya existe. Introduzca un nombre exclusivo.",
        NMRangeAlert: "Introduzca un rango válido",
        FORMULAS: "FÓRMULAS",
        DataValue: "Valores:",
        Value: "Valores",
        Formula: "fórmulas",
        MissingParenthesisAlert: "Su fórmula le falta un parenthesis--) o (. Verificar la fórmula, y luego añadir los paréntesis en el lugar apropiado.",
        UnsupportedFile: "Archivo no soportado",
        IncorrectPassword: "No se puede abrir el archivo de hoja de cálculo o de la contraseña proporcionada",
        InvalidUrl: "Por favor, especifique el URL adecuado",
        Up: "Arriba",
        Down: "Abajo",
        Sheet: "Hoja",
        Workbook: "Libro de trabajo",
        Rows: "por Filas",
        Columns: "por columnas",
        FindReplace: "Encuentra Reemplazar",
        FindnReplace: "Buscar y reemplazar",
        Find: "Encontrar",
        Replace: "Reemplazar",
        FindLabel: "Encontrar que:",
        ReplaceLabel: "Remplazar con:",
        ReplaceAll: "Reemplaza todo",
        Close: "Cerca",
        FindNext: "Buscar siguiente",
        FindPrev: "Buscar anterior",
        Automatic: "Automático",
        Manual: "Manual",
        Settings: "ajustes",
        MatchCase: "Mayúsculas y minúsculas",
        MatchAll: "Corresponder con el contenido de toda la celda",
        Within: "Dentro:",
        Search: "Buscar:",
        Lookin: "Pase a ver:",
        ShiftRight: "Desplazar las celdas hacia la derecha",
        ShiftBottom: "Desplazar las celdas hacia abajo",
        EntireRow: "Fila completa",
        EntireColumn: "Toda la columna",
        ShiftUp: "Desplazar las celdas hacia arriba",
        ShiftLeft: "Desplazar las celdas hacia la izquierda",
        Direction: "Dirección:",
        GoTo: "Ir",
        GoToName: "Ir:",
        Reference: "Referencia:",
        Special: "Especial",
        Select: "Seleccionar",
        Comments: "comentarios",
        Formulas: "fórmulas",
        Constants: "constantes",
        RowDiff: "diferencias fila",
        ColDiff: "diferencias entre columnas",
        LastCell: "última celda",
        CFormat: "formatos condicionales",
        Blanks: "Los espacios en blanco",
        GotoError: "Error",
        GotoLogicals: "Logicals",
        GotoNumbers: "Números",
        GotoText: "Texto",
        FindSelect: "Buscar y seleccionar",
        Comment: "Comentario",
        NewComment: "Nuevo",
        InsertComment: "Insertar comentario",
        EditComment: "Editar",
        DeleteComment: "Eliminar comentario",
        DeleteCommentContent: "Eliminar el mensaje seleccionado.",
        HideComment: "Ocultar comentario",
        Next: "Siguiente",
        NextContent: "Saltar a la siguiente comentario.",
        Previous: "Anterior",
        PreviousContent: "Salta a la anterior comentario.",
        ShowHide: "Mostrar / Ocultar comentario",
        ShowHideContent: "Mostrar u ocultar el comentario en la celda activa.",
        ShowAll: "Mostrar todos los comentarios",
        ShowAllContent: "Mostrar todos los comentarios en la hoja.",
        UserName: "Nombre de usuario",
        Hide: "Esconder",
        Unhide: "en Mostrar",
        Add: "Añadir",
        DropAlert: "¿Desea reemplazar los datos existentes?",
        PutCellColor: "Ponga Color seleccionado de la célula a la tapa",
        PutFontColor: "Ponga la fuente seleccionada en color a la tapa",
        WebPage: "Página web",
        WorkSheet: "Hoja de trabajo de referencia",
        SheetReference: "hoja de referencia",
        InsertHyperLink: "Insertar hipervínculo",
        HyperLink: "Hiperenlace",
        EditLink: "Editar enlace",
        OpenLink: "Enlace abierto",
        HyperlinkText: "Texto:",
        RemoveLink: "Eliminar enlace",
        WebAddress: "Dirección web:",
        CellAddress: "Referencia de la celda:",
        SheetIndex: "Seleccionar un lugar en este documento",
        ClearAll: "Limpiar todo",
        ClearFormats: "formatos claras",
        ClearContents: "Borrar contenido",
        ClearComments: "claras Comentarios",
        ClearHyperLinks: "claro hipervínculos",
        SortFilter: "Ordenar y filtrar",
        SortFilterContent: "Organizar los datos por lo que es más fácil de analizar.",
        NumberStart: "Mínimo:",
        NumberEnd: "Máximo:",
        DecimalStart: "Mínimo:",
        DecimalEnd: "Máximo:",
        DateStart: "Fecha de inicio:",
        DateEnd: "Fecha final:",
        ListStart: "Fuente:",
        FreeText: "se introduce Mostrar mensaje de error de datos no válidos",
        ListEnd: "Referencia de la celda:",
        TimeStart: "Hora de inicio:",
        TimeEnd: "Hora de finalización:",
        TextLengthStart: "Mínimo:",
        TextLengthEnd: "Máximo:",
        CommentFindEndAlert: "Hoja de cálculo llega al final del libro. ¿Quieres continuar con la revisión desde el principio del libro?",
        InsertSheet: "Insertar",
        DeleteSheet: "Borrar",
        RenameSheet: "Rebautizar",
        MoveorCopy: "Mover o copiar",
        HideSheet: "Esconder",
        UnhideSheet: "en Mostrar",
        SheetRenameAlert: "El nombre ya fue escogido. Pruebe uno diferente.",
        SheetRenameEmptyAlert: "Ha escrito un nombre no válido para una hoja. Asegúrese de que: <ul> <li> El nombre que escriba no exceda de 31 caracteres </ li> <li> El nombre no contiene ninguno de los siguientes caracteres:. \ /? * [O] </ li> <li> Usted no dejar el nombre en blanco. </ Li> </ ul>",
        SheetDeleteAlert: "No se puede deshacer la eliminación de las hojas, y que podría estar eliminando algunos datos. Si usted no lo necesita, haga clic en OK para borrar.",
        SheetDeleteErrorAlert: "Un libro debe contener al menos una hoja de trabajo visible. Para ocultar, eliminar o mover la hoja seleccionada, primero debe insertar una nueva hoja o mostrar una hoja que ya está oculto.",
        CtrlKeyErrorAlert: "Este comando no se puede utilizar en múltiples selecciones.",
        MoveToEnd: "Ir al final",
        Beforesheet: "Antes de la ficha técnica:",
        CreateaCopy: "Crear una copia",
        AutoFillOptions: "Las células de copia / relleno de la serie / llenado Sólo Formateo / Fill sin formato Relleno / flash",
        NumberValidationMsg: "Introduzca sólo dígitos",
        DateValidationMsg: "Introduzca única fecha",
        Required: "Necesario",
        TimeValidationMsg: "El tiempo que ha introducido para el tiempo es válido.",
        CellAddrsValidationMsg: "La referencia no es valida.",
        PivotTable: "Tabla dinámica",
        PivotTableContent: "Fácil de organizar y resumir datos complejos en una tabla dinámica.",
        NumberTab: "Número",
        AlignmentTab: "Alineación",
        FontTab: "Fuente",
        FillTab: "Llenar",
        TextAlignment: "alineación del texto",
        Horizontal: "Horizontal:",
        Vertical: "Vertical:",
        Indent: "Sangrar",
        TextControl: "control de texto",
        FontGroup: "Fuente:",
        FontStyle: "Estilo de fuente:",
        Size: "Tamaño:",
        PSize: "Tamaño de página",
        Effects: "efectos:",
        StrikeThrough: "que atraviesa",
        Overline: "overline",
        NormalFont: "fuente normal",
        Preview: "Avance",
        PreviewText: "AaBbCc zyzz",
        Line: "Línea",
        Presets: "presets",
        None: "Ninguna",
        Outline: "contorno",
        AllSide: "Todos los lados",
        InsCells: "Las células de inserción",
        InsRows: "Insertar filas de hoja",
        InsCols: "Insertar columnas de hoja",
        InsSheet: "Insertar hoja",
        DelCells: "eliminar celdas",
        DelRows: "Eliminar filas de hojas",
        DelCols: "Eliminar columnas Hoja",
        DelSheet: "eliminar hoja",
        HyperLinkAlert: "La dirección de este sitio no es valid.Check la dirección e inténtelo de nuevo.",
        ReplaceData: "Todo listo. Hicimos / reemplazos.",
        NotFound: "No hemos podido encontrar lo que busca. Seleccione la configuración de pestaña para más formas de buscar",
        Data: "Datos:",
        Allow: "Permitir:",
        IgnoreBlank: "ignorar espacio en blanco",
        NotFind: "No se puede encontrar el partido para reemplazar",
        FreezeRow: "Fila superior congelar",
        FreezeColumn: "Freeze primera columna",
        UnFreezePanes: "Movilizar paneles",
        DestroyAlert: "¿Está seguro de que quiere destruir el libro actual sin guardar y crear un nuevo libro?",
        ImageValAlert: "Sube sólo archivos de imagen",
        Pictures: "Imágenes",
        PicturesTitle: "Desde el archivo",
        PicturesContent: "Insertar imágenes desde el ordenador o desde otros ordenadores que están conectados.",
        ImportAlert: "¿Está seguro de que quiere destruir el libro actual sin guardar y abrir un nuevo libro?",
        UnmergeCells: "Separar celdas",
        MergeCells: "Combinar células",
        MergeAcross: "Al otro lado de fusionar",
        MergeAndCenter: "Combinar y Centro",
        MergeAndCenterContent: "Combinar y centrar el contenido de las celdas seleccionadas en una nueva célula más grande.",
        MergeCellsAlert: "La fusión de células mantiene valor de celda única parte superior izquierda y descarta los demás valores.",
        MergeInsertAlert: "Esta operación hará que algunas celdas combinadas de desinstalar. Desea continuar ?",
        Axes: "ejes",
        PHAxis: "Horizontal primaria",
        PVAxis: "Vertical primaria",
        AxisTitle: "Título del eje",
        CTNone: "Ninguna",
        CTCenter: "Centrar",
        CTFar: "Lejos",
        CTNear: "Cerca",
        DataLabels: "Etiquetas de datos",
        DLNone: "Ninguna",
        DLCenter: "Centrar",
        DLIEnd: "Dentro End",
        DLIBase: "Dentro de Base",
        DLOEnd: "terminar en el exterior",
        ErrorBar: "Barras de error",
        Gridline: "Las líneas de cuadrícula",
        PMajorH: "Primary Major Horizontal",
        PMajorV: "Mayor primaria Vertical",
        PMinorH: "Horizontal primaria Menor",
        PMinorV: "Mayor primaria Vertical",
        Legend: "leyendas",
        LNone: "Ninguna",
        LLeft: "Izquierda",
        LRight: "Derecha",
        LBottom: "Fondo",
        LTop: "Parte superior",
        ChartTitleDlgText: "Introducción del título",
        ChartTitle: "Título",
        InvalidTitle: "Ha escrito un nombre no válido para el título.",
        CorrectFormat: "Seleccione el formato de archivo correcto",
        ResetPicture: "Reset Picture",
        ResetPictureContent: "Descartar todos los cambios de formato realizados en esta imagen.",
        PictureBorder: "Frontera del cuadro",
        PictureBorderContent: "Elige el color, ancho y estilo de línea para el contorno de su forma.",
        ResetSize: "Restablecer del cuadro y del tamaño",
        Height: "Altura",
        Width: "Anchura",
        ThemeColor: "Colores del tema",
        NoOutline: "sin Esquema",
        Weight: "Peso",
        Dashes: "Los guiones",
        ColumnChart: "Columna 2-D / columna 3D",
        ColumnChartTitle: "Insertar gráfico de columnas",
        ColumnChartContent: "Utilizar este tipo de gráfico para comparar visualmente los valores a través de unas pocas categorías.",
        BarChart: "2-D / Bar 3D",
        BarChartTitle: "Insertar gráfico Bar",
        BarChartContent: "Utilizar este tipo de gráfico para comparar visualmente los valores a través de unas pocas categorías cuando el gráfico se muestra la duración o el texto categoría es larga.",
        StockChart: "Radar",
        StockChartTitle: "Insertar gráfico radial",
        StockChartContent: "Utilizar este tipo de gráfico para mostrar los valores relativos a un punto central.",
        LineChart: "2-D Line",
        LineChartTitle: "Insertar Gráfico de líneas",
        LineChartContent: "Utilizar este tipo de gráfico para mostrar tendencias en el tiempo (años, meses y días) o categorías.",
        AreaChart: "2-D Área / 3D Area",
        AreaChartTitle: "Insertar gráfico Área",
        AreaChartContent: "Utilizar este tipo de gráfico para mostrar tendencias en el tiempo (años, meses y días) o categorías. Lo utilizan para destacar la magnitud del cambio en el tiempo.",
        ComboChart: "Combo",
        PieChart: "Tarta",
        PieChartTitle: "Insertar el gráfico de sectores / buñuelo",
        PieChartContent: "Utilizar este tipo de gráfico para mostrar las proporciones de un todo. Utilizarlo cuando el total de sus números es 100%.",
        ScatterChart: "Dispersión",
        ScatterChartTitle: "Insertar Scatter (X, Y) Gráfico",
        ScatterChartContent: "Utilizar este tipo de gráfico para mostrar la relación entre conjuntos de valores.",
        ClusteredColumn: "Columna; & nbsp agrupado",
        StackedColumn: "Columna; & nbsp apilada",
        Stacked100Column: "100% & nbsp; & nbsp apilada; Columna",
        Cluster3DColumn: "3D & nbsp; & nbsp clúster; Columna",
        Stacked3DColumn: "3D & nbsp; & nbsp apilada; Columna",
        Stacked100Column3D: "3D & nbsp; 100% & nbsp; & nbsp apilada; Columna",
        ClusteredBar: "Agrupado & nbsp; Bar",
        StackedBar: "Stacked & nbsp; Bar",
        Stacked100Bar: "100% & nbsp; & nbsp apilada; Bar",
        Cluster3DBar: "3D & nbsp; & nbsp clúster; Bar",
        Stacked3DBar: "3D & nbsp; & nbsp apilada; Bar",
        Stacked100Bar3D: "3D & nbsp; 100% & nbsp; & nbsp apilada; Bar",
        Radar: "Radar",
        RadarMarkers: "Radar & nbsp; & nbsp ancho; Marcadores",
        LineMarkers: "Línea & nbsp; & nbsp ancho; Marcadores",
        Area: "Zona",
        StackedArea: "Stacked & nbsp; Área",
        Stacked100Area: "100% & nbsp; & nbsp apilada; Área",
        Pie: "Tarta",
        Pie3D: "3-D & nbsp; Pie",
        Doughnut: "Rosquilla",
        Scatter: "Dispersión",
        ChartRange: "Rango Gráfico",
        XAxisRange: "Introduzca rango del eje X:",
        YAxisRange: "Introduzca rango del eje Y:",
        LegendRange: "Introduzca rango de leyenda:",
        YAxisMissing: "Introduzca rango del eje Y para crear diagrama",
        InvalidYAxis: "rango del eje Y debe estar dentro del rango seleccionado",
        InvalidXAxis: "rango del eje X debe estar dentro del rango seleccionado",
        InvalidLegend: "Leyenda rango debe estar dentro del rango seleccionado",
        InvalidXAxisColumns: "rango del eje X debe estar dentro de una sola columna",
        FreezePanes: "Inmovilizar paneles",
        FreezePanesContent: "Congelar una parte de la hoja para mantenerlo visible mientras se desplaza por el resto de la hoja.",
        PasteTitle: "Pegar (Ctrl + V)",
        PasteContent: "Añadir el contenido del portapapeles al documento.",
        PasteSplitContent: "Elija una opción de pegado, como mantener el formato o pegar sólo el contenido.",
        CutTitle: "Cortar (Ctrl + X)",
        CutContent: "Retire la selección y colocarla en el portapapeles para que pueda pegarlo en otro lugar.",
        CopyTitle: "Copia (Ctrl + C)",
        CopyContent: "Ponga una copia de la selección en el portapapeles para que pueda pegarlo en otro lugar.",
        FPTitle: "Copiar formato",
        FPContent: "Al igual que el aspecto de una selección particular? Usted puede solicitar que la mirada de otros contenidos en el documento.",
        BoldTitle: "Negrita (Ctrl + B)",
        BoldContent: "Haga su texto en negrita.",
        ItalicTitle: "Cursiva (Ctrl + I)",
        ItalicContent: "Poner en cursiva el texto.",
        ULineTitle: "Línea inferior (Ctrl + U)",
        ULineContent: "Subrayar el texto.",
        LineTrTitle: "Que atraviesa (Ctrl + 5)",
        LineTrContent: "Cruzar algo fuera dibujando una huelga a través de él.",
        UndoTitle: "Deshacer (Ctrl + Z)",
        UndoContent: "Deshacer la última acción.",
        RedoTitle: "Rehacer (Ctrl + Y)",
        RedoContent: "Rehacer la última acción.",
        TableTitle: "Tabla (Ctrl + T)",
        HyperLinkTitle: "Añadir un hipervínculo (Ctrl + K)",
        HyperLinkContent: "Crear un enlace en su documento para un rápido acceso a las páginas web y archivos. <br /> <br /> Los hipervínculos también te puede llevar a lugares en su documento.",
        NewCommentTitle: "Inserte un comentario",
        NewCommentContent: "Añadir una nota sobre esta parte del documento.",
        RefreshTitle: "Refrescar",
        RefreshContent: "Obtener los últimos datos de la fuente conectada a la celda activa",
        FieldListTitle: "Lista de campos",
        FieldListContent: "Mostrar u ocultar la lista de campos. <br /> <br /> La lista de campos le permite agregar y quitar campos de su informe de tabla dinámica",
        AddChartElement: "Añadir elemento de gráfico",
        AddChartElementContent: "Añadir elementos a la tabla creada.",
        SwitchRowColumn: "Cambiar de fila / columna",
        SwitchRowColumnContent: "Intercambiar los datos a lo largo del eje.",
        MergeAlert: "No podemos hacer eso a una celda combinada.",
        UnhideDlgText: "Mostrar hoja:",
        ChartThemes: "Temas tabla",
        ChartThemesContent: "Escoja un tema nuevo para el gráfico.",
        ChangePicture: "Cambiar imagen",
        ChangePictureContent: "Cambiar a una imagen diferente, que preserva el formato y el tamaño de la imagen actual.",
        ChangeChartType: "Cambiar tipo de gráfico",
        SelectData: "Seleccionar datos",
        SelectDataContent: "Cambiar el rango de los datos incluidos en la tabla.",
        Sum: "Suma",
        Average: "Promedio",
        CountNumber: "Cuenta numeros",
        Max: "Max",
        Min: "min",
        ChartType: "Cambiar tipo de gráfico",
        ChartTypeContent: "Cambiar a un tipo de gráfico diferente.",
        AllCharts: "todos Listas",
        defaultfont: "Defecto",
        LGeneral: "General",
        LCurrency: "Moneda",
        LAccounting: "Contabilidad",
        LDate: "Fecha",
        LTime: "Hora",
        LPercentage: "Porcentaje",
        LFraction: "Fracción",
        LScientific: "Científico",
        LText: "Texto",
        LCustom: "Personalizado",
        FormatSample: "Muestra",
        Category: "Categoría:",
        Top: "Parte superior",
        Center: "Centrar",
        Bottom: "Fondo",
        Left: "Izquierda (sangría)",
        Right: "Derecha",
        Justify: "Justificar",
        GeneralTxt: "Formato de celdas generales no tienen formato de número específico.",
        NegativeNumbersTxt: "Los números negativos",
        ThousandSeparatorTxt: "Utilice 1000 Separador",
        DecimalPlacesTxt: "Decimales:",
        TextTxt: "Formato de celdas de texto se tratan como texto, incluso cuando un número está en la célula. La célula se muestra exactamente como introducido.",
        BoldItalic: "Negrita cursiva",
        Regular: "Regular",
        HyperLinkHide: "<< Selección en el Documento >>",
        InvalidSheetIndex: "Especificar SheetIndex adecuada",
        HugeDataAlert: "El archivo es demasiado grande para abrir.",
        ImportExportUrl: "Dar dirección URL de importación / exportación y vuelve a intentarlo.",
        TitleColumnChart: "Columna agrupada / columnas apiladas / 100% apilada Columna / 3D agrupado Columna / 3D columnas apiladas / columna 3D 100% apilada",
        TitleBarChart: "Agrupado Bar / Barra apilada / 100% apilada Bar / 3D de barras agrupadas / 3D de barras apiladas / 3D 100% de barras apiladas",
        TitleRadarChart: "Radar / radar con marcadores",
        TitleLineChart: "Línea / Línea con marcadores",
        TitleAreaChart: "Área / Área apilada / 100% Área apilada",
        TitlePieChart: "Pie / 3D Pie / buñuelo",
        TitleScatterChart: "Dispersión",
        BetweenAlert: "El máximo debe ser mayor o igual que el mínimo.",
        BorderStyles: "Sólido / La / punteada",
        FPaneAlert: "Panel de congelación no se aplica para la primera celda",
        ReplaceNotFound: "Hoja de cálculo no puede encontrar una coincidencia.",
        BlankWorkbook: "libro en blanco",
        SaveAsExcel: "Guardar como Excel",
        SaveAsCsv: "Guardar como CSV",
        Design: "DISEÑO",
        NewName: "Nuevo nombre",
        FormulaBar: "Barra de formulas",
        NameBox: "nombre de la carpeta",
        NumberValMsg: "Los valores decimales no se pueden utilizar para las condiciones numéricas.",
        NumberAlertMsg: "Introduzca sólo dígitos.",
        ListAlert: "rango de celdas es incorrecta, Por favor, introduzca el rango de celdas correcta.",
        ListValAlert: "El origen de la lista debe ser una lista delimitada, o una referencia a una sola fila o columna.",
        ListAlertMsg: "El valor que ha introducido no es válido",
        AutoFillTitle: "Opciones de Autocompletar",
        NewSheet: "Hoja nueva",
        FullSheetCopyPasteAlert: "No se puede pegar porque el área Copia y área de pegado no son del mismo tamaño.",
        Heading: "encabezamientos",
        Gridlines: "Las líneas de cuadrícula",
        Firstsheet: "Desplazarse a la primera hoja",
        Lastsheet: "Desplazarse hasta la última hoja",
        Nextsheet: "Desplazarse a la siguiente hoja",
        Prevsheet: "Desplazarse a la hoja anterior",
        ProtectWorkbook: "proteger libro",
        UnProtectWorkbook: "Desproteger libro",
        ProtectWBContent: "Mantener a otros de hacer cambios estructurales para su libro",
        Password: "Contraseña",
        ConfirmPassword: "Re Introduzca la contraseña para proceder:",
        PasswordAlert1: "La confirmación de contraseña no es idéntica.",
        PasswordAlert2: "Porfavor ingrese una contraseña.",
        PasswordAlert3: "La contraseña que proporcionó no es correcta. Compruebe que la tecla Bloq Mayús está apagado y asegúrese de utilizar correctamente las mayúsculas.",
        Protect: "esta protegido.",
        Lock: "Bloquear celda",
        Unlock: "desbloquear la célula",
        Protectsheet: "Hoja de protección",
        protectsheettooltip: "Evitar cambios no deseados de los demás, al limitar su capacidad de editar",
        Unprotect: "Desproteger hoja",
        LockAlert: "La célula que está intentando cambiar está en hoja protegida. Para realizar cambios, haga clic en Desproteger hoja en la ficha Revisar.",
        CreateRule: "Nueva regla",
        NewRule: "Nueva regla de formato",
        NewRuleLabelContent: "valores de formato, donde esta fórmula es verdadera:",
        InsertDeleteAlert: "no se permite esta operación. La operación está tratando de cambiar las celdas de una tabla en la hoja de cálculo.",
        ReadOnly: "La gama que está intentando cambiar contiene leer sólo las células.",
        CreatePivotTable: "Crear tabla dinámica",
        Range: "Distancia:",
        ChoosePivotTable: "Elegir dónde desea que la tabla dinámica para ser colocado",
        NewWorksheet: "nueva hoja de cálculo",
        ExistingWorksheet: "Hoja de trabajo existente",
        Location: "Ubicación:",
        Refresh: "Refrescar",
        PivotRowsAlert: "Este comando requiere al menos dos filas de datos de origen. No se puede utilizar el comando en una selección en una sola fila.",
        PivotLabelsAlert: "El nombre del campo de tabla dinámica no es válido, Para crear un informe de tabla dinámica, debe utilizar los datos que se organiza como una lista con las columnas etiquetadas. Si va a cambiar el nombre de un campo de tabla dinámica, debe escribir un nuevo nombre para el campo.",
        FieldList: "Lista de campos",
        MergeSortAlert: "Para ello, todas las celdas combinadas tienen que ser del mismo tamaño.",
        FormulaSortAlert: "El rango de ordenación con la fórmula no puede ser ordenada.",
        MergePreventInsertDelete: "no se permite esta operación. La operación está tratando de desplazar a las células de combinación en la hoja de cálculo.",
        FormulaRuleMsg: "Por favor, introduzca el formato correcto.",
        MovePivotTable: "Mover tabla dinámica",
        MovePivotTableContent: "Mover la tabla dinámica a otro lugar en el libro.",
        ClearAllContent: "Eliminar campos y filtros.",
        ChangeDataSource: "Modificar",
        ChangeDataSourceContent: "Cambiar los datos de origen para esta tabla dinámica",
        ChangePivotTableDataSource: "Cambiar origen de datos de tabla dinámica",
        TotalRowAlert: "no se permite esta operación. La operación está tratando de cambiar las celdas de una tabla en la hoja de cálculo. Haga clic en OK para continuar con la fila entera.",
        CellTypeAlert: "Esta operación no está permitido en el tipo de células gama aplicada.",
        PivotOverlapAlert: "Un informe de tabla dinámica no se pueden superponer otro informe de tabla dinámica",
        NoCellFound: "No se encontraron células",
        };

        ej.Pager.Locale["es-ES"] = {
            pagerInfo: "{0} de {1} páginas ({2} artículos)",
            firstPageTooltip: "Ir a la primera página",
            lastPageTooltip: "Ir a la última página",
            nextPageTooltip: "Ir a la página siguiente",
            previousPageTooltip: "Ir a la página anterior",
            nextPagerTooltip: "Ir al siguiente Pager",
            previousPagerTooltip: "Ir a Pager anterior"
        };

    </script>
</asp:Content>

