<%@ Page Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" CodeBehind="DefaultFunctionality.aspx.cs" Inherits="WebSampleBrowser.PPTX.DefaultFunctionality" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>Essential Presentation library has support for creating, editing and converting PowerPoint slides.</p>
	<p>This sample demonstrates how slides can be created with simple text in a PowerPoint presentation.</p>
	<p><b>Features:</b></p>	
	<p>
		<ul>
		<li>Create a PowerPoint presentation from scratch with few lines of code.</li>
		<li>Open the existing PowerPoint presentation from file system or stream, modify and save it back.</li>		
		<li>Save the PowerPoint presentation to a local file, stream, or stream it to the client browser.</li>
		<li>Create, edit and convert shapes.</li>		
		<li>Create, edit and convert text.</li>
		<li>Add and manipulate single-level and multilevel lists equivalent to Microsoft PowerPoint.</li>
		<li>Create, edit and convert charts.</li>
		<li>Create, edit and convert SmartArt diagrams.</li>
		<li>Create, edit and convert tables with different styles.</li>
		<li>Copy and paste PowerPoint slides with source and destination paste options.</li>
		<li>Create, reply and edit comments.</li>
		<li>Create, edit and convert notes pages.</li>
		<li>Apply, edit and convert formatting of slide elements.</li>
		</ul>
	</p>
    <table width="100%">
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label6" runat="server" Text="Click the button to view a presentation document generated by Essential Presentation.  Please note that MS PowerPoint viewer is required to view the resultant document."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                               <asp:Button Width="165px" Style="margin-right: 3px" ID="Button1" Height="27px" runat="server"
                                     OnClick="Button1_Click" Text="Create Presentation" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>
