<%@ Page Title="Presentation-OLE Object-ASP.NET-SYNCFUSION"   Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" CodeBehind="InsertOLEObject.aspx.cs" Inherits="WebSampleBrowser.PPTX.InsertOLEObject" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
	<p>Essential Presentation library has support for insert and open a OLE object in a PowerPoint presentation.</p>
    <p>This sample demonstrates how to insert and open a OLE Object in PowerPoint presentation.</p>
    <p><b>Features:</b></p>	
    <p>
        <ul>
        <li>Add new OLE Object into a PowerPoint slide.</li>
        <li>Extract a embedded OLE Object data.</li>
        <li>Gets the file path of a linked OLE Object.</li>
        <li>Gets the file name of a OLE Object.</li>
        </ul>		
    </p>	
    <table width="100%">
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label1" runat="server" Text="Click the button to view a presentation document generated by Essential Presentation.  Please note that MS PowerPoint viewer is required to view the resultant presentation."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                                <asp:Button Width="165px" Style="margin-right: 3px" ID="Button2" Height="27px" runat="server"
                                     OnClick="Button1_Click" Text="Create Presentation" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label3" runat="server" Text="Click the button to view a embedded OLE document opened by Essential Presentation. Please note that Microsoft Word is required to view the embedded Docx document."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                                <asp:Button Width="165px" Style="margin-right: 3px" ID="Button3" Height="27px" runat="server"
                                     OnClick="Button2_Click" Text="Open Embedded File" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>

