<%@ Page Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" CodeBehind="ModifyingChart.aspx.cs" Inherits="WebSampleBrowser.PPTX.ModifyingChart" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
	<p>Essential Presentation library has support for modifying charts in a PowerPoint presentation.</p>
    <p>This sample demonstrates how to customize the appearance of a chart in a PowerPoint presentation.</p>
	<p><b>Features:</b></p>	
	<p>
		<ul>
		<li>Create, edit and convert more than 80 chart types.</li>
		<li>Create custom charts by adding combinations from different chart types.</li>
		<li>Convert individual chart in a PowerPoint slide to image.</li>
		<li>Modify, include and remove chart elements like axes, label, legend and chart title.</li>
		<li>Edit color for chart elements like chart area and plot area of an existing chart.</li>
		</ul>
	</p>
    <table width="100%">
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label6" runat="server" Text="Click the button to view a presentation document with charts generated by Essential Presentation.  Please note that MS PowerPoint viewer is required to view the resultant document."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                                <asp:Button Width="165px" Style="margin-right: 3px" ID="Button1" Height="27px" runat="server"
                                     OnClick="Button1_Click" Text="Create Presentation" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>
