<%@ Page Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" CodeBehind="Slides.aspx.cs" Inherits="WebSampleBrowser.PPTX.Slides" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
	<p>Essential Presentation library has support for creating, editing and converting slides in a PowerPoint presentation.</p>
    <p>This sample demonstrates how to create slides with simple text, table and image in a PowerPoint presentation.</p>
	<p><b>Features:</b></p>	
	<p>
		<ul>
		<li>Support for 9 pre-defined slide layouts while creating new slides.</li>
        <li>Add, rearrange, duplicate, and delete slides in PowerPoint presentation.</li>
        <li>Slides can be copied and pasted to the same or different PowerPoint presentation.</li>
        <li>Slides can be formatted with variety of formatting options equivalent to Microsoft PowerPoint.</li>
		</ul>
	</p>	
    <table width="100%">
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label6" runat="server" Text="Click the button to view a presentation document generated by Essential Presentation.  Please note that MS PowerPoint viewer is required to view the resultant document."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                               <asp:Button Width="165px" Style="margin-right: 3px" ID="Button1" Height="27px" runat="server"
                                     OnClick="Button1_Click" Text="Create Presentation" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>
