<%@ Page Title="Presentation-Tables-ASP.NET-SYNCFUSION"   Language="C#" MasterPageFile="~/Samplebrowser.Master" AutoEventWireup="true" CodeBehind="Tables.aspx.cs" Inherits="WebSampleBrowser.PPTX.Tables" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
	<p>Essential Presentation library has support for creating, editing and converting tables in a PowerPoint presentation.</p>
    <p>This sample demonstrates how to add tables in a PowerPoint presentation.</p>
	<p><b>Features:</b></p>	
	<p>
		<ul>
		<li>Format tables with 6 pre-defined table style options to format the entire rows and columns.</li>
		<li>Format tables with 74 pre-defined table styles to change the borders and shading of the table.</li>
		<li>Create, modify, and format tables to keep data organized.</li>
		<li>Cell and row-level operations like adding, inserting, deleting of rows are supported.</li>
		<li>Built-in table styles are available equivalent to Microsoft PowerPoint table styles.</li>
		</ul>
	</p>
    <table width="100%">
        <tr>
            <td align="left">
                <div>
                    <asp:Label Width="100%"  Style="text-align: justify;"
                        ID="label6" runat="server" Text="Click the button to view a presentation document generated by Essential Presentation.  Please note that MS PowerPoint viewer is required to view the resultant document."></asp:Label>
                </div>
                <br />
                <div style="border: solid 0px #788DB3; padding: 5px 7px 5px 7px;">
                    <table width="100%">
                        <tr>
                            <td align="left" width="100%" cellpadding="0" cellspacing="0" border="0">
                               <asp:Button Width="165px" Style="margin-right: 3px" ID="Button1" Height="27px" runat="server"
                                     OnClick="Button1_Click" Text="Create Presentation" />
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>

