<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="BudgetPlanner.aspx.cs" Inherits="WebSampleBrowser.XlsIO.BudgetPlanner" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        It can be difficult to decide how much you can afford to save or how much you can
        spend every month. This budget planner application created using Essential XlsIO
        helps you determine your monthly disposable income. Enter your annual income and
        expenses in the Quick Budget sheet to assess your financial position.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <div>                        
                        <br />
                        <table width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="left">
                                    <asp:Label ID="Label2" runat="server" Text="SaveAs:"></asp:Label>
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="True"/> 
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                 
                                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document"
                                                Width="138px" />
                                    &nbsp;
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Input Template" Width="148px" />
                                    </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
