<%@ Page Title="XlsIO-Chart Worksheet-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ChartWorksheet.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ChartWorksheet" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        A chart sheet is a worksheet in a workbook that has its own sheet name. These are
        employed, in order to give a clearer view, when using a large chart with a lot data.
        The chart is linked to the worksheet data and is updated automatically when there
        are changes.
    </p>
    <p>
        The <strong>IChart</strong> interface is the in-memory representation of the chart
        worksheet in an Excel workbook. These are used to create charts and to set properties
        for those charts. The <strong>IChartSerie</strong> interface can be used to set
        various formats for a series.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO.
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="left">
                                    <asp:label runat="server" id="label1" text="Save As :"></asp:label>
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                                    <asp:radiobutton  style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" />
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                        width="200px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>

