<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ComputeSpecificFormula.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ComputeSpecificFormula" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        This sample demonstrates how Essential XlsIO can compute the values of a formula
        entered during run time using the calculate engine.
    </p>
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <div>
                        <asp:label width="150%" style="text-align: justify;" id="label6" runat="server" text="Click the button to view an Excel spreadsheet generated by Essential XlsIO. Please note that MS Excel Viewer or MS Excel is required to view the resultant document."></asp:label>
                    </div>
                    <br />
                    <div>
                        <table width="120%" style="padding: 0px 3px 0px 3px" cellpadding="0" cellspacing="0"
                            border="0">
                            <tr>
                                <td align="left">
                                    <asp:label width="65px" runat="server" id="label1" text="Save As:"></asp:label>
                                    <asp:radiobutton autopostback="true" id="rdButtonXls" runat="server" groupname="Group1"
                                        text="Excel 2003" />
                                    <asp:radiobutton autopostback="true" style="margin-left: 5px" id="rdButtonXlsx" runat="server"
                                        groupname="Group1" text="Excel 2007" />
                                    <asp:radiobutton autopostback="true" style="margin-left: 5px" id="rdButtonXlsx2010" runat="server"
                                        groupname="Group1" text="Excel 2010" />
                                    <asp:radiobutton autopostback="true" style="margin-left: 5px" id="rdButtonXlsx2013" runat="server"
                                        groupname="Group1" text="Excel 2013" checked="True" />
                                </td>
                                <td align="right">
                                    <asp:button width="250px" id="Button1" runat="server" onclick="Button2_Click" text="Open sample workbook in Excel" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                    <div>
                        <asp:menu id="CategoryMenu" runat="server" font-bold="True" forecolor="Black" dynamichorizontaloffset="2"
                            font-names="Verdana" orientation="Horizontal" staticsubmenuindent="10px" onmenuitemclick="CategoryMenu_MenuItemClick"
                            font-size="12px">
                            <StaticMenuItemStyle HorizontalPadding="15px" VerticalPadding="2px" BackColor="#AEB7CF" />
                            <StaticHoverStyle BackColor="#f7e6c3" />
                            <StaticSelectedStyle BackColor="#5d7fb7" ForeColor="White" />
                            <Items>
                                <asp:MenuItem Text="Sheet1" Selected="true"></asp:MenuItem>
                                <asp:MenuItem Text="Sheet2"></asp:MenuItem>
                            </Items>
                        </asp:menu>
                        <asp:multiview id="MultiView1" runat="server" activeviewindex="0">
                            <asp:View ID="GroupingView" runat="server">
                                <asp:GridView Width="100%" ID="GridView1" runat="server" DataSource='<%# GetData(0) %>'
                                    BorderColor="#DAE5FF" BorderStyle="Solid" Font-Names="Verdana" Font-Size="Small"
                                    AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                                    ShowFooter="True" OnRowDataBound="GridView1_RowDataBound">
                                    <RowStyle BorderColor="#DAE5FF" BorderStyle="Solid" BorderWidth="1px" Height="22px"
                                        HorizontalAlign="Left" VerticalAlign="Middle" />
                                    <SelectedRowStyle BackColor="Info" />
                                    <HeaderStyle BackColor="LightSteelBlue" BorderColor="#DAE5FF" BorderStyle="Solid"
                                        Height="25px" HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <FooterStyle BackColor="Moccasin" BorderStyle="None" Font-Bold="True" Height="25px"
                                        HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:GridView>
                            </asp:View>
                            <asp:View ID="SortingView" runat="server">
                                <asp:GridView Width="100%" ID="GridView2" runat="server" DataSource='<%# GetData(1) %>'
                                    BorderColor="#DAE5FF" BorderStyle="Solid" Font-Names="Verdana" Font-Size="Small"
                                    OnRowDataBound="GridView2_RowDataBound">
                                    <HeaderStyle BackColor="LightSteelBlue" Height="25px" />
                                    <RowStyle BorderColor="#DAE5FF" BorderStyle="Solid" Height="22px" HorizontalAlign="Left"
                                        VerticalAlign="Middle" />
                                </asp:GridView>
                            </asp:View>
                        </asp:multiview>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
