<%@ Page Title="XlsIO-Conditional Formatting-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ConditionalFormatting.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ConditionalFormatting" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        Microsoft Office Excel provides enhanced conditional formatting support. Conditional
        formatting allows the application of formatting to one or more cells based on cell
        value or the value of a formula. This sample illustrates the use of Essential XlsIO
        to programmatically set conditional formatting on a range of cells using color scales,
        icon sets, and data bars.
    </p>
    <p>
        Essential XlsIO also supports the application of more than three conditional formats
        for the same cell in an XLSX file, similar to Excel 2007. It is important to note
        that it was not possible to apply more than three conditional formats in earlier
        versions of Excel.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="left">
                                    <asp:label runat="server" id="label1" text="Save As :"></asp:label>
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />                                                                       
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document" Width="164px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>

