<%@ Page Title="XlsIO-Create-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="CreateSpreadsheet.aspx.cs" Inherits="WebSampleBrowser.XlsIO.CreateSpreadsheet" %>

<asp:Content ID="content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        Essential XlsIO has support for creating richly formatted spreadsheets
        from scratch, without any dependence on Excel. Advanced features, like data validation,
        conditional formatting, and charts, can also be used in this approach. This sample
        demonstrates the creation of a simple, multi-sheet workbook. Formats like XLS,
        XLSX, CSV, Excel Template, Excel Macro Enabled Template
        are supported and demonstrated here.
    </p>
    <br />
    <p>
       Excel document is widley used to manipulate and visualize data that enables data analytics in ease. 
       Essential XlsIO supports to create an Excel document without any dependancy of Microsoft Excel in few lines of code.
       This sample demonstrates the creation of a simple spreadsheet.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                  <div>
                      <table width="90%" cellpadding="0" cellspacing="0" border="0">
                          <tr>
                              <td align="left">
                                  <asp:label width="60px" runat="server" id="label1" text="Save As:"></asp:label>
                                  <asp:radiobutton id="rdButtonXls" runat="server" groupname="Group1" text="XLS" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXlsx" Checked="true" runat="server" groupname="Group1"
                                      text="XLSX" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonCsv" runat="server" groupname="Group1"
                                      text="CSV" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXltx" runat="server" groupname="Group1"
                                      text="XLTX" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXltm" runat="server" groupname="Group1"
                                      text="XLTM" />
                                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                  <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                      width="150" />
                              </td>
                          </tr>
                      </table>
                  </div>
              </td>
            </tr>
        </table>
    </div>
</asp:Content>

