<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="DataValidation.aspx.cs" Inherits="WebSampleBrowser.XlsIO.DataValidation" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        <strong>Data Validation</strong> is a feature of Excel that helps validate the information
        entered into a worksheet. It provides users with the following options:
        <br />
        <br />
        * Provides a list of choices<br />
        * Restricts entries to a specific type or size<br />
        * Creates custom settings<br />
        <br />
        Essential XlsIO has support for reading and writing data validations. This sample
        focuses on writing a data validation in an Excel template.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="left">                                    
                                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                        width="200px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
