<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="DocumentProperties.aspx.cs" Inherits="WebSampleBrowser.XlsIO.DocumentProperties" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">

    <p>
        Document properties are details about a file. They include information about title,
        author name, subject, keywords, etc. You can also have custom properties. Essential
        XlsIO provides support for custom properties.
    </p>
    </br>
    <p>
        Excel provides various page-setup options to control the way a spreadsheet fits
        onto paper; this is done using the &quot;Page Setup&quot; dialog. This allows you
        to select the size and orientation of the paper, the width of the margins, the headers
        and footers for each page, and the order of printing cells for sheets that will
        take several pieces of paper.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
       <table width="100%" cellpadding="0" cellspacing="0" border="0">
           <tr>
               <td>
                   <asp:label runat="server" id="label2" text="Save As:"/>
                   <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                   <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                   <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                        width="200px" />
               </td>
           </tr>
       </table>
    </div>               
</asp:Content>
