<%@ Page Title="XlsIO-Edit Macro-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="EditMacro.aspx.cs" Inherits="WebSampleBrowser.XlsIO.EditMacro" %>

<asp:Content ID="content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <div class="rowdiv">
        Essential XlsIO supports creating macro files from scratch and edit the macro code programmatically.This sample demonstrates editing macro code  and saves the final document in different formats like Excel 97-2003, macro-enabled Excel template and macro-enabled Excel workbook.
        <br />
        <br />
        <b>Features:</b>
        <br />
        <br />
        <ul>
            <li>Open existing macro-enabled Excel template.</li>
            <li>Modify the macro code to change the chart type.</li>
            <li>Save the edited macro-enabled file in various file formats (XLS, XLSM, XLTM).</li>
        </ul>
        <br />
        <br />
        <p>
            Click the button to view the Excel spreadsheet generated by Essential XlsIO. Please
            note that Microsoft Excel Viewer or Excel is required to view the resultant document.
        </p>
    </div>
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                  <div>
                      <table width="90%" cellpadding="0" cellspacing="0" border="0">
                          <tr>
                              <td align="left">
                                  <asp:label width="60px" Font-Bold="true" runat="server" id="label1" text="Save As:"></asp:label>
                                  <br />
                                  <br />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXls" Checked="true" runat="server" groupname="Group1"
                                      text="XLS" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXltm" runat="server" groupname="Group1"
                                      text="XLTM" />
                                  <asp:radiobutton style="margin-left: 5px" id="rdButtonXlsm" runat="server" groupname="Group1"
                                      text="XLSM" />
                                  <br />
                                  <br />
                                  <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                      width="150" />
                              </td>
                          </tr>
                      </table>
                  </div>
              </td>
            </tr>
        </table>
    </div>
</asp:Content>

