<%@ Page Title="XlsIO-Encrypt and Decrypt-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="EncryptionDecryption.aspx.cs" Inherits="WebSampleBrowser.XlsIO.EncryptionDecryption" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    <p>
        Encryption is a password-based method to protect workbook data. Encryption converts
        the data into an incomprehensible form and it restricts users from accessing the
        data.
    </p>
    <p>
        Decryption is the process of converting encrypted data back to its original
        form to make it comprehensible to read from a workbook.
    </p>
    <p>
        <strong>Features</strong>:</p>
    <p class="style1">
        A password to encrypt a workbook can be set in Excel in the <strong>Office Menu</strong>-><strong>Prepare</strong>-><strong>Encrypt
            Document</strong> option.</p>
    <p>
        <strong>Password to open: </strong>This password is encrypted to help protect data
        from unauthorized access.</p>
    <ul>
        
            <p>
                <strong>Password</strong> used in this sample: <strong>syncfusion</strong>
        
        </p></ul>
    <p>
        <strong>Note:</strong> Password protection of a workbook file is different from
        the workbook structure and window protection that can be set in the <strong>Protect
            Workbook </strong>dialog box.
    </p> 
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                    <asp:RadioButton Style="margin-left: 10px" ID="rdBtnXls" runat="server" GroupName="Group1" Text="XLS" />
                    <asp:RadioButton Style="margin-left: 30px" ID="rdBtnXlsx" runat="server" GroupName="Group1" Text="XLSX" Checked="true" />
                </td>
            </tr>
            <tr>
                <td>                   
                    <div style="margin-top: 5px">
                        <br />
                        <asp:Button style="margin-left:2px" ID="Button1" runat="server" OnClick="Button1_Click" Text="Encrypt" Width="120px" />
                        <asp:Button style="margin-left:15px" ID="Button2" runat="server" OnClick="Button2_Click" Text="Decrypt" Width="120px" />                                
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
<asp:Content ID="Content3" runat="server" contentplaceholderid="StyleSection">
    <style type="text/css">
        .auto-style1 {
            width: 315px;
        }
    </style>
</asp:Content>


