<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ExcelToODS.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ExcelToODS" %>

<asp:Content ID="content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        The OpenDocument format (ODF) is a free and open file format for electronic office documents originally developed by Sun for the Open Office suite. XlsIO saves Excel files to OpenDocument Spreadsheet (ODS), a file format for Excel documents. OpenDocument is currently an OASIS and ISO standard.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
	 <br />
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                  <div>
                      <table width="90%" cellpadding="0" cellspacing="0" border="0">
                          <tr>
                              <td align="left">
                                  <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Excel to ODS"
                                      width="150" />
                              </td>
                          </tr>
                      </table>
                  </div>
              </td>
            </tr>
        </table>
    </div>
</asp:Content>
