<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeBehind="ExternalFormula.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ExternalFormula" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        External Formulas that refers to a value in another workbook. An external formula is a reference to a cell or range of cells in another workbook.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <b>Read Formula from the template document</b>
                    <table style="margin-top: 10px" width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td align="left" valign="top">
                                 <asp:Label ID="Label1" runat="server" Text="Formula String" Width="110px"  Font-Bold="True"></asp:Label>
                            </td>
                            <td align="left">
                                &nbsp;&nbsp;
                            </td>
                            <td align="left">
                                <asp:Label ID="txtFormula" runat="server" ReadOnly="true"></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                &nbsp;
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                 <asp:Label ID="Label2" runat="server" Text="Computed Value" Width="110px"  Font-Bold="True"></asp:Label>
                            </td>
                            <td align="left">
                                &nbsp;&nbsp;
                            </td>
                            <td align="left">
                                <asp:Label ID="txtFormulaNumber" runat="server" ReadOnly="true"></asp:Label>
                            </td>
                        </tr>
                    </table>
                    <table style="margin-top: 10px" width="35%" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td align="left">
                                <asp:Button Width="150px" ID="Button3" runat="server" Text="Read Formula" OnClick="Button3_Click" />
                            </td>
                            <td align="left">
                                <asp:Button Width="150px" ID="Button1" runat="server" Text="Write Formula" OnClick="Button1_Click" />
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                &nbsp;
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
</asp:content>