<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="FormatCells.aspx.cs" Inherits="WebSampleBrowser.XlsIO.FormatCells" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
   
    <p>
        Formatting worksheets makes them more attractive and easy to read and use. Microsoft
        Excel provides various options to set the font, font size, color, and background.
    </p></br>
    <ul>
        <li>&nbsp;&nbsp;The <strong>Format Cells</strong> dialog box in Excel contains six tabs,
            each with several characteristics that allow the setting of various formatting options
            of a cell.</li>
        <li>&nbsp;&nbsp;These help set the number formats, alignment, text control operations,
            font and font styles, and borders for the cells.</li>
    </ul>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td>
                                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" />
                                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <asp:Button ID="Button2" runat="server" OnClick="Button1_Click" Text="Create Document"
                                        Width="200px" />
                                </td>                                
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
