<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="FormControls.aspx.cs" Inherits="WebSampleBrowser.XlsIO.FormControls" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
        <p>
        Essential XlsIO can read and write form controls like text boxes,
        check boxes, and combo boxes.
    </p>
    <br/>
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>

    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document"
                                        Width="200px" />                                
                </td>
            </tr>
        </table>
    </div>
</asp:content>
