<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="Formulas.aspx.cs" Inherits="WebSampleBrowser.XlsIO.Formulas" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        Formulas are entries in Excel that have an equation that calculates the value to
        be displayed. A typical formula might contain cells, constants, and even functions.
        Essential XlsIO has support for reading and writing formulas.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <b>Read Formula from the template document</b>
                    <br />
                    <div style="margin-top: 5px; line-height: 30px">
                        <asp:Label ID="Label1" runat="server" Text="Computed Value" Width="110px"></asp:Label>
                        <asp:Label Width="248px" ID="txtFormulaNumber" runat="server" ReadOnly="true" Font-Bold="True"></asp:Label>
                        <br />
                        <asp:Label ID="Label2" runat="server" Text="Formula String" Width="110px"></asp:Label>
                        <asp:Label Width="248px" ID="txtFormula" runat="server" ReadOnly="true" Font-Bold="True" ></asp:Label>
                    </div>
                    <table style="margin-top: 3px" width="35%" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td align="left">
                                <asp:Button Width="150px" ID="Button1" runat="server" Text="Write Formula" OnClick="Button1_Click" />
                            </td>
                            <td align="left">
                                <asp:Button Width="150px" style="margin-left: 10px" ID="Button3" runat="server" Text="Read Formula" OnClick="Button3_Click" />
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                &nbsp;
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
