<%@ Page Title="XlsIO-Group Shapes-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="GroupShapes.aspx.cs" Inherits="WebSampleBrowser.XlsIO.GroupShapes" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        Essential XlsIO allows to group multiple shapes and ungroup the shapes in worksheet. The IGroupShape interface is the in-memory representation of the
        group shapes in an Excel workbook.
    </p>
    <br />
    <p>Features:</p>
    <br />
    <p> This sample demonstrates following features: </p>
    <br />
    <ul>
        <li>Grouping multiple shapes into a single group shape.</li>
        <li>Ungroup the group shape and all its inner shapes.</li>
    </ul>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <br />
    <div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <asp:RadioButton GroupName="html" ID="groupRBtn" Checked="true" runat="server" Text="Group" />
                    &nbsp;&nbsp;
                    <asp:RadioButton style="margin-left: 20px" GroupName="html" ID="ungroupRBtn" runat="server" Text="Ungroup" />
                    &nbsp;&nbsp;
                    <asp:RadioButton style="margin-left: 20px" GroupName="html" ID="ungroupRBtnAll" runat="server" Text="Ungroup All"/>
                </td>
            </tr>
        </table>
        <br />
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document" Width="120px" />
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Input Template" Width="120px" />
                </td>
            </tr>
        </table>
    </div>
</asp:content>

