<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ImportExportDataTable.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ImportExportDataTable" %>

<asp:content id="content2" contentplaceholderid="ControlsSection" runat="server">
    <p>
        Essential XlsIO has support for creating richly formatted spreadsheets
        from scratch, without any dependence on Excel. Advanced features, like data validation,
        conditional formatting, and charts, can also be used in this approach. This sample
        demonstrates the creation of a simple, multi-sheet workbook. Formats like Excel
        97-2003, Excel 2007, CSV, Excel 2007 Template, Excel 2007 Macro Enabled Template
        are supported and demonstrated here.</p>
    <br />
    <p>
        In this sample, a new instance of XlsIO is created. This instance has no open workbooks.
        A workbook is created with the <strong>IWorkbook</strong> interface. This workbook
        has three worksheets by default and can be created based according to need. The<strong>
            IRange</strong> interface can be used to access the cell and write the content.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <br />
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr style="margin-top: 5px;">
                <td>                    
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>                                
                                <td>
                                    <asp:label width="90px" runat="server" id="label1" text="Save As:"></asp:label>
                                    <asp:radiobutton Width ="75px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                                    <asp:radiobutton Width ="75px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                                </td>
                                <td>
                                    <asp:Button ID="btnexport" runat="server" OnClick="Button2_Click" Text="Export to Excel"
                                        Width="200px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                    <div>
                        <asp:GridView Width="100%" BorderColor="AliceBlue" AllowPaging="true" BorderStyle="Solid"
                            EnableSortingAndPagingCallbacks="True" ID="DataGrid1" runat="server">
                            <HeaderStyle BackColor="LightSteelBlue" BorderColor="#DAE5FF" BorderStyle="Solid" />
                        </asp:GridView>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
