<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="ImportJSON.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ImportJSON" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">  
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <br />
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr style="margin-top: 5px;">
                <td>
                    <div>
                        <table width="120%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td>
                                    <asp:label runat="server" id="label1" text="Save As :"></asp:label>
                                    <asp:radiobutton style="margin-left: 10px" id="rdBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                                    <asp:radiobutton  style="margin-left: 10px" id="rdBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" />
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document" width="200px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
