<%@ Page Title="XlsIO-Import From Grid-ASP.NET-SYNCFUSION"    MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeFile="ImportFromGrid.aspx.cs" Inherits="WebSampleBrowser.XlsIO.ImportFromGrid" %>
   <asp:content id="content2" contentplaceholderid="ControlsSection" runat="server">
    <div>
        XlsIO supports to import data from GridView into Excel worksheet with formatting.
        <br />
         <br />
         <p>
            Click the button to view an Excel spreadsheet generated by Essential XlsIO.
            Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
        </p>
        <asp:Panel ID="Panel1" runat="server" ScrollBars="Vertical" Height="290" Width="400">
        <asp:GridView ID="gridView" runat="server">
        </asp:GridView>
        </asp:Panel>
        <br />
        Import Options:&nbsp;&nbsp;&nbsp;
        <b><asp:CheckBox ID="chbHeader" runat="server" Checked="true" Text="Import Header" />&nbsp;&nbsp;</b>
        <b><asp:CheckBox ID="chbStyle" runat="server" Checked="true" Text="Import Style" /></b>
        <br />
        <br />
        Save As&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;
        <b><asp:RadioButton ID="rdButtonXls" GroupName="rdb" runat="server"  Text="XLS" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>
        <b><asp:RadioButton ID="rdButtonXlsx" GroupName="rdb" runat="server"  Checked="true" Text="XLSX" /></b>
        <br />
        <br />
        <asp:Button ID="btnCreateExcel" runat="server" onclick="btnCreateExcel_Click" 
            Text="Import" Width="200px" />
    </div>
    </asp:content>


