<%@ Page Title="XlsIO-Import Nested Collection-ASP.NET-SYNCFUSION"  MasterPageFile="~/samplebrowser.master"  Language="C#" AutoEventWireup="true" Inherits="WebSampleBrowser.XlsIO.ImportNestedCollection" CodeBehind="ImportNestedCollection.aspx.cs" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        Essential XlsIO allows you to import data directly from nested collection objects with import data layout and group options.
    </p>
	<p>
        This sample demonstrates the usage of Nested Collection objects using Essential XlsIO.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="630px" cellpadding="0" cellspacing="0" border="0">
            <tr>
            <td>                
				 <div>
                    <table width="400px" cellpadding="0" cellspacing="0" border="0">
                        <tr> 
						<td style="width:130px" align="left" >
						<asp:Label runat="server" id="label1" Text="Layout Options" Font-Bold="true"></asp:Label>
						</td>
						<td align="left">
                        <asp:Dropdownlist id="LayoutOptions" runat="server" Width="180px"> </asp:Dropdownlist>
                        </td>
						</tr>
                    </table>
                </div>
                <br />
                <div>
                   <table cellpadding="0" cellspacing="0" border="0">
                        <tr> 
						<td style="width:130px" />
						<td>
                           <asp:Checkbox id="checkbox" runat="server" Text="" TextAlign="Left" OnCheckedChanged="ChckedChanged" AutoPostBack="true" />
                           <asp:label id="label2" runat="server" Font-Bold="true">Apply Group</asp:label>
						</td>
						</tr>
                    </table>
                </div>
                <asp:panel runat="server"  id="groupOptions" visible="false">
				<br/>
                    <table  cellpadding="0" cellspacing="0" border="0" visible="false">
                        <tr>
                            <td style="width:130px" />
                            <td>
                                <asp:label id="label3" runat="server" Font-Bold="true">Options</asp:label>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td style="width:130px" />
                            <td>
                                <asp:Radiobutton id="rdbExpand" runat="server" Text=" Expand" checked="true" groupname="radio" OnCheckedChanged="rdb_CheckedChanged" AutoPostBack="true"/>
                            </td>
                        </tr>
                        <tr>
                            <td style="width:130px" />
                            <td>
                                <asp:Radiobutton id="rdbCollapse" runat="server" Text=" Collapse at Level" groupname="radio" OnCheckedChanged="rdb_CheckedChanged" AutoPostBack="true"/>
                            </td>
                            <td>
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox id="textBox" runat="server" Visible="false" Text="1" Width="40px"/>
                            </td>
                        </tr>
                    </table>
                </asp:panel>
                <br/>
                <div>
                    <table cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td style="width:130px"/>
                             <td>
                                <asp:button id="Button1" runat="server" text="Create Excel" onclick="Button1_Click" AutoPostBack="true" Width="165px"/>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
            </tr>
        </table>
    </div>
</asp:Content>
<%--<asp:Content ID="temp" ContentPlaceHolderID="EventSection" runat="server" Visible="false">
    <asp:HiddenField ID="iconsetTemp" runat="server"/>
    <asp:HiddenField ID="iconidTemp" runat="server"/>
</asp:Content>--%>
<%--<asp:Content ID="Content3" ContentPlaceHolderID="ScriptSection" runat="server">
    <script type="text/javascript">
        function onChange(e) {
            var ctry = $('#<%=selectIcon.ClientID%>').data("ejComboBox");
            ctry.option({ enabled: true, query: new ej.Query().where('Id', 'equal', e.model.value), value: null });
            $("#<%= iconsetTemp.ClientID %>").val(e.model.value);
        }
        function onIconId(e) {
            $("#<%= iconidTemp.ClientID %>").val(e.model.value);
        }
    </script>
</asp:Content>--%>
