<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="InteractiveFeatures.aspx.cs" Inherits="WebSampleBrowser.XlsIO.InteractiveFeatures" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
   
    <p>
        Excel has the following interactive features:</p>
    <ul>
        <li>
            <p>Comments</p>
        </li>
        <li>
            <p>Hyperlinks</p>
        </li>
    </ul>
    <p>
        Comments are notes used to provide context to your data in Excel cells. They are
        basically used to denote the content in a cell. Text in the comments can be richly
        formatted to emphasize a comment concerning the cell.</p></br>
    <p>
        A hyperlink is a rich feature in Excel that allows the user to instantly access
        another place in the current workbook, another workbook, or a file associated with
        another application. A hyperlink can be inserted in a cell or a shape in Excel.
        This allows you to enter a cell reference in the current workbook. You can also
        browse to another workbook, a different file, or a Web page.&nbsp; You can even
        enter an e-mail address.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>
                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document"
                                        Width="200px" />                                
                </td>
            </tr>
        </table>
    </div>
</asp:content>
