<%@ Page Title="" Language="C#" MasterPageFile="~/samplebrowser.master" AutoEventWireup="true"
    CodeFile="OleObject.aspx.cs" Inherits="WebSampleBrowser.XlsIO.OleObject" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        Essential XlsIO now supports insertion of OleObjects.</p></br>
    <p>
        This sample demonstrates how a OleObject can be inserted. It is possible to insert
        it as Embed or Link. For both types, location and size can be adjusted.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <br />
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <div>
                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>                              
                                <td>
                                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Spreadsheet"
                                        Width="200px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
