<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="Performance.aspx.cs" Inherits="WebSampleBrowser.XlsIO.Performance" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">

    <p>
        Essential XlsIO provides support to fill data to given range of cells in the worksheet.
    </p>
    <br />
    <p>This sample demonstrates how to increase the performance of XlsIO </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="650px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <div>

                        <table width="80%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="left">
                                    <asp:label id="Label2" runat="server" text="Enter the Number of Rows" width="218px"></asp:label>
                                </td>
                                <td align="left">
                                    <asp:textbox width="199px" id="textBoxRows" text="50000" runat="server" height="25px"></asp:textbox>
                                </td>
                            </tr>   
                            <tr>
                                <td>
                                    <br />
                                </td>
                            </tr>                         
                            <tr>
                                <td align="left">
                                    <asp:label id="Label3" runat="server" text="Enter the Number of Columns" width="219px"></asp:label>
                                </td>
                                <td align="left">
                                    <asp:textbox width="199px" id="textBoxColumns" text="50" runat="server" height="25px"></asp:textbox>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                                    <asp:radiobutton style="margin-left: 20px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                                    <asp:radiobutton style="margin-left: 20px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" />                                   
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:button id="Button1" runat="server" text="Create Document"
                                        width="200px" onclick="Button1_Click" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:label id="lblStatus" runat="server" width="218px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
