<%@ Page Title="XlsIO-Performance-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="Performance.aspx.cs" Inherits="WebSampleBrowser.XlsIO.Performance" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">

	<p>Essential XlsIO is known for its high performance and simple APIs that have most of the functionalities of Excel.</p>
	<br />
	<br />
	<b>Features:</b>
	<br />
	<br />
	<ul>
		<li>Creating rich, large reports with styles.</li>
		<li>Performance optimization methods.</li>
		<li>Import on Save option to serialize data while saving the workbook, which is recommended for imprting large data without formatting.</li>
	</ul>
	<b>Notes:</b>
    <br />
	<br />
	<ul>
		<li>When more styles are added, it is recommended that you use global styles within BeginUpdate and EndUpdate calls.</li>
		<li>The use of IMigrant Range will reduce the amount of memory used when large amounts of strings are involved.</li>
	</ul>
    <br />
    <p>This sample demonstrates how to increase the performance of XlsIO </p>
    <br />
    <p>
        Click the button to view the Excel document generated by Essential XlsIO. 
        Please note that Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <div>
            <div>
            <asp:label id="Label2" runat="server" text="Enter the Number of Rows" width="218px"></asp:label>
            <asp:textbox width="100px" id="textBoxRows" text="50000" runat="server" height="16px"></asp:textbox>
            <br />
            <br />
            <asp:label id="Label3" runat="server" text="Enter the Number of Columns" width="219px"></asp:label>
            <asp:textbox width="100px" id="textBoxColumns" text="50" runat="server" height="16px"></asp:textbox>
            </div>
            <br />
            <div>
            <asp:label runat="server" id="label1" text="Save As:"></asp:label>
            <asp:radiobutton style="margin-left: 20px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" OnCheckedChanged="rBtnXls_CheckedChanged" AutoPostBack="true"/>
            <asp:radiobutton style="margin-left: 20px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" OnCheckedChanged="rBtnXlsx_CheckedChanged" AutoPostBack="true"/>                                   
            </div>
            <div class="option">
            <asp:CheckBox id="import" runat="server" Text="Import on Save" AutoPostBack="true"/>
            <br />
            <p style="font-size:12px">Import on Save option directly serialize data while saving the workbook.</p>
            </div>
            <div>     
                <asp:button id="Button1" runat="server" text="Create Document"
                width="200px" onclick="Button1_Click" />
            <br />
            <asp:label id="lblStatus" runat="server" width="218px" />
            </div>

        </div>
    </div>
</asp:Content>

