<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="PivotChart.aspx.cs" Inherits="WebSampleBrowser.XlsIO.PivotChart" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
        The Pivot Chart provides a graphical representation of pivot table
        data, allowing for rapid analysis of information. Essential XlsIO has an API for
        creating a pivot chart from pivot table data while allowing you to use different
        chart types.
    <br />
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p> 
    <div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td align="center">
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document"
                                        Width="200px" />
                </td>
            </tr>
        </table>
    </div>
</asp:content>
