<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="PivotTable.aspx.cs" Inherits="WebSampleBrowser.XlsIO.PivotTable" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    To better organize large reports, Excel allows summarizing data through pivot table
    insertion. Excel 2007 supplies various built-in styles for pivot tables, allowing
    the creation of a pivot table with rich formats and more flexibility.
    <br />
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td align="left" colspan="2">
                    <asp:Label Width="200px" runat="server" ID="label2" Text="Page Filter:"></asp:Label>
                    <asp:CheckBox Style="margin-left: 5px" ID="ckbPageFilter" runat="server"
                        Text="Page Filter"  oncheckedchanged="chkPageFilter_CheckedChanged" AutoPostBack="True"/>
                    <asp:CheckBox Style="margin-left: 50px" ID="ckbMultiplePageFilter" runat="server" Text="Apply Multiple Filter" 
                        oncheckedchanged="ckbMultiplePageFilter_CheckedChanged" AutoPostBack="True"/>
                    <br /><br />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label Width="200px" runat="server" ID="label3" Text="Row and Column Filter:"></asp:Label>
                    <asp:CheckBox Style="margin-left: 5px" ID="ckbRowFilter" runat="server" 
                        Text="Row Filter" oncheckedchanged="ckbRowFilter_CheckedChanged" AutoPostBack="True"/>
                    <asp:CheckBox Style="margin-left: 50px" ID="ckbColumnFilter" runat="server" 
                        Text="Column Filter" oncheckedchanged="ckbColumnFilter_CheckedChanged" AutoPostBack="True"/>
                    <br /><br />
                </td>
            </tr>
            <tr>
                <td colspan="2" align="left">
                    <asp:RadioButton Style="margin-left: 55px" ID="rdbRCLabelFilter" runat="server" GroupName="Group4"
                        Checked="true" Text="Apply Label Filter" Enabled="False" />
                    <asp:RadioButton Style="margin-left: 35px" ID="rdbRCValueFilter" runat="server" GroupName="Group4"
                        Text="Apply Value Filter" Enabled="False" />
                    <asp:RadioButton Style="margin-left: 35px" ID="rdbRCMultipleFilter" runat="server"
                        GroupName="Group4" Text="Apply Multiple Filter" Enabled="False" />
                    <br /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Button Style="margin-left: 55px" ID="Button1" runat="server" Text="Create Document"
                                            Width="200px" OnClick="Button1_Click" />                
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button Style="margin-left: 35px" ID="Button2" runat="server" Text="Customize Pivot Table"
                                            Width="200px" OnClick="Button2_Click" />
                </td>
            </tr>
        </table>
    </div>
</asp:content>
