<%@ Page Title="XlsIO-Pivot Layout-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="PivotLayout.aspx.cs" Inherits="WebSampleBrowser.XlsIO.PivotLayout" %>

<asp:Content ID="content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <div class="rowdiv">
        To better organize large reports, Excel allows summarizing data through pivot table
        insertion. Microsoft Excel supplies various built-in styles for pivot tables, allowing
        the creation of a pivot table with rich formats and more flexibility.
        <br />
        <br />
        <b>Features:</b>
        <br />
        <br />
        <ul>
            <li>Create and layout pivot table from template data</li>
            <li>Format pivot table cells with cell styles</li>
            <li>Convert pivot table to PDF</li>
        </ul>
        <br />
        <p>
            Click the button to view the Excel spreadsheet generated by Essential XlsIO. Please
            note that Microsoft Excel Viewer or Excel is required to view the resultant document.
        </p>
    </div>
    <br />
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                   
                  <div>
                      <table width="90%" cellpadding="0" cellspacing="0" border="0">
                          <tr>
                              <td>
                                  <asp:label Font-Bold="true" runat="server" id="label1" text="Layout options:"></asp:label>
                                  <asp:radiobutton style="margin-left: 10px" id="rdButtonCompact" runat="server" groupname="Group1" Checked="true" 
                                      text="Compact" />
                                  &nbsp;&nbsp;
                                  <asp:radiobutton style="margin-left: 10px" id="rdButtonOutline" runat="server" groupname="Group1"
                                      text="Outline" />
                                  &nbsp;&nbsp;
                                  <asp:radiobutton style="margin-left: 10px" id="rdButtonTabular" runat="server" groupname="Group1"
                                      text="Tabular" />
                              </td>
                          </tr>
                      </table>
                      <br />
                      <table>
                         <tr>
                            <td>
                                <asp:Button ID="Button1" runat="server" Text="Create Pivot Table"
                                                        Width="155px" OnClick="Create_Pivot_Table_Click" />                
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <asp:Button ID="Button2" runat="server" Text="Convert to PDF"
                                                        Width="155px" OnClick="Convert_to_PDF_Click" />
                            </td>
                        </tr>
                      </table>
                  </div>
              </td>
            </tr>
        </table>
    </div>
</asp:Content>

