<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="RowColumnManipulations.aspx.cs" Inherits="WebSampleBrowser.XlsIO.RowColumnManipulations" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        This sample demonstrates the manipulations that can be performed with rows and columns
        using Essential XlsIO.</p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td align="left" class="auto-style1">
                    <asp:label runat="server" id="label1" text="Save As:"></asp:label>
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="formatgrp" text="XLS" />
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="formatgrp" text="XLSX" checked="true" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document" Width="130px" />
                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Input Template" Width="130px" />                                
                </td>
            </tr>
        </table>
    </div>
</asp:content>
<asp:Content ID="Content3" runat="server" contentplaceholderid="StyleSection">
    <style type="text/css">
        .auto-style1 {
            width: 852px;
        }
    </style>
</asp:Content>

