<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
     CodeBehind="SalesInvoice.aspx.cs" Inherits="WebSampleBrowser.XlsIO.SalesInvoice" %>

<asp:Content ID="content2" ContentPlaceHolderID="ControlsSection" runat="server">
    <p>
        This sample focuses on creating an application using an Essential XlsIO and ADO
        connection.
    </p>
    <br />
    <p>
        An Excel template is read by XlsIO and an invoice is generated for the given invoice
        ID; this is done by fetching data corresponding to the particular ID from the Northwind
        database. Price, total, and other calculations are done with simple formulas using
        Essential XlsIO.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
 <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td align="left">
                    <asp:Label Height="25px" Style="vertical-align: middle;" ID="Label1" runat="server"
                                        Text="Select the OrderID :" />
                    <asp:DropDownList ID="DropDownList1" Width="150px" runat="server" />
                </td>
            </tr>
            <tr>
                <td>
                    <br />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:label runat="server" id="label2" text="Save As:"></asp:label>
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXls" runat="server" groupname="Group1" text="XLS" />
                    <asp:radiobutton style="margin-left: 10px" id="rBtnXlsx" runat="server" groupname="Group1" text="XLSX" checked="true" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button Width="200px" ID="Button1" runat="server" Text="Create Document" OnClick="Button1_Click"></asp:Button>                    
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
