<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="StylesAndFormatting.aspx.cs" Inherits="WebSampleBrowser.XlsIO.StylesAndFormatting" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
   
    <p>
        Excel 2013 is known for its various styles and formatting that enhance its appearance.
        It supports gradient styles and a number of new colors. Essential XlsIO also supports
        formatting cells with gradient and indexed colors. These colors are closer to the
        32-bit colors of Excel. You can also set styles and formatting that support BIFF8
        format.</p>
    <p>
        This sample demonstrates Essential XlsIO's support for various styles and formatting
        in XLSX format. An interior method of <strong>IStyle</strong> is used to set gradient
        styles.
    </p>
    <p>
        <strong>Note:</strong> This can apply gradient styles only for the Excel 2007 format.
    </p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <br />
    <div>
        <table id="PanelTable" width="750px" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td>                    
                    <div>
                        <table width="60%" cellpadding="0" cellspacing="0" border="0">
                            <tr>                                
                                <td>
                                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Document"
                                        Width="137px" />                                    
                                </td>
                                <td>
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Input Template" Width="137px" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</asp:content>
