<%@ Page Title="XlsIO-Table Formula-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="TableFormula.aspx.cs" Inherits="WebSampleBrowser.XlsIO.TableFormula" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    In Excel 2013 and later versions, calculated column formula can be used in tables.
	   
        XlsIO supports reading and writing calculated column formula from Excel 2013 format.
    <br />
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr style="margin-top: 5px;">
                <td align="left">
                    <asp:button id="Button1" runat="server"  onclick="Button1_Click" text="Create Document"
                                        width="206px" />                          
                </td>
            </tr>
        </table>
    </div>
</asp:Content>

