<%@ Page Title="XlsIO-Tables-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="Tables.aspx.cs" Inherits="WebSampleBrowser.XlsIO.Tables" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    Microsoft Office Excel provides table support that makes managing and analyzing
        data easy and efficient. These tables come with specific style support.
   
        XlsIO supports reading and writing tables in Excel files. Tables can be created
        from any input range and a Total Row can be inserted in the table. Styles can also
        be applied.
    <br />
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td align="center">
                    <asp:button id="Button1" runat="server" onclick="Button1_Click" text="Create Document"
                                        width="206px" />                               
                </td>
            </tr>
        </table>
    </div>
</asp:Content>

