<%@ Page Title="XlsIO-Worksheet Protection-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="WorksheetProtection.aspx.cs" Inherits="WebSampleBrowser.XlsIO.WorksheetProtection" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
  
    <p>
        Microsoft Excel offers a special way for protecting specific data and certain worksheets,
        with or without a password. This prevents anyone from changing, moving, or deleting
        important data.</p></br>
    <p>
        Excel allows editing or locking a range of cells in a protected worksheet using
        the <strong>Protection </strong>tab in the <strong>Format Cells</strong> dialog
        box. By default, all cells are locked, but are not hidden when the worksheet is
        protected. Worksheets can be protected by choosing the <strong>Tools</strong> -
        <strong>Protection</strong> - <strong>Protect Sheet </strong>option in Excel.</p>
     <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td align="center">
                    <asp:Button ID="Button3" Width="150px" runat="server" OnClick="Button1_Click" Text="Lock Worksheet" />
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button4" Width="150px" runat="server" OnClick="Button2_Click" Text="Unlock Worksheet" />                              
                </td>
            </tr>
        </table>
    </div>
</asp:content>

