<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true"
    CodeFile="WorkBookProtection.aspx.cs" Inherits="WebSampleBrowser.XlsIO.WorkBookProtection" %>

<asp:content id="Content2" contentplaceholderid="ControlsSection" runat="server">
    
    <p>
        You can lock the structure of a workbook, preventing users from adding or deleting
        worksheets or displaying hidden worksheets. You can also prevent users from changing
        the size or position of worksheet windows. Workbook structure and window protection
        apply to the entire workbook.</p></br>
    <p>
        To protect a workbook, point to <strong>Protection</strong> on the <strong>Tools</strong>
        menu, and click <strong>Protect Workbook</strong>.</p>
    <p>
        You can choose the elements you want to protect (workbook structure, windows, or
        both) by selecting or clearing the following check boxes.</p>
    <br />
    <p>
        Click the button to view an Excel spreadsheet generated by Essential XlsIO. 
        Please note that Microsoft Excel Viewer or Microsoft Excel is required to view the resultant document.
    </p>
    <div>
        <table id="PanelTable" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>               
                <td align="center">
                    <asp:Button ID="Button1" Width="150px" runat="server" OnClick="Button1_Click" Text="Protect Workbook" />
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button2" Width="150px" runat="server" OnClick="Button2_Click" Text="Unprotect Workbook" />                               
                </td>
            </tr>
        </table>
    </div>
</asp:content>
