//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSampleBrowser.Tab {
    
    
    public partial class AjaxContent {
        
        /// <summary>
        /// DefaulttasdbContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.Tab DefaulttasdbContent;
        
        /// <summary>
        /// ASPNET control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.TabItem ASPNET;
        
        /// <summary>
        /// MVC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.TabItem MVC;
        
        /// <summary>
        /// WPF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.TabItem WPF;
    }
}
