<%@ Page Title="DocIO-Word to HTML-ASP.NET-SYNCFUSION"   MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeBehind="DocToHTML.aspx.cs" Inherits="WebSampleBrowser.DocIO.DocToHTML" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ControlsSection" runat="server">
    This sample illustrates how to convert Word document to HTML using Essential DocIO.
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>
                    <div>
                        <div>
                            <br style="line-height: 10px" />
                        </div>
                        <b>Select Document</b>
                        <div>
                            <br style="line-height: 10px" />
                        </div>
                        <div>
                            <asp:FileUpload ID="FileUpload1" Width="385px" runat="server" />
                        </div>
                        <br />
                        <div>
                            <asp:Label Width="100%" Style="text-align: justify;" ID="label6" runat="server" Text="Click the button below to view the HTML file generated by Essential DocIO."></asp:Label>
                        </div>
                        <br />
                        <div>
                            <table width="100%" cellpadding="10" cellspacing="0" border="0">
                                <tr>
                                    <td align="left">
                                        <asp:Button ID="btnDocToHTML" Width="150px" Height="27px" runat="server" Text="Convert to HTML"
                                            OnClick="btnDocToHTML_Click" />
                                    </td>
                                </tr>
                            </table>
                            <div>
                                <br style="line-height: 10px" />
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div>
        <asp:Label Width="100%" ForeColor="red" Style="text-align: justify;" ID="label1"
            runat="server" Text=""></asp:Label></div>
</asp:Content>

