<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeBehind="FindAndReplace.aspx.cs" Inherits="WebSampleBrowser.DocIO.FindAndReplace" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    This sample illustrates finding a text and replacing it with a new text using Essential DocIO.
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>
                    <div>
                        <table width="100%">
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="left" style="height: 29px">
                                    <asp:Label runat="server" ID="label1" Text="Dear "></asp:Label>
                                    <asp:TextBox ID="textBoxName" runat="server"></asp:TextBox>,
                                </td>
                                <td align="right" style="height: 29px">
                                    <asp:Label ID="labelDate" runat="server">Date</asp:Label>,
                                    <asp:Label ID="labelDay" runat="server">Day</asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:TextBox ID="textBoxBody" runat="server" Height="288px" TextMode="MultiLine"
                                        Width="448px"></asp:TextBox>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td align="center">
                                    <asp:Label ID="Label3" runat="server">Yours truly,</asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td align="right" colspan="2" style="height: 31px">
                                    <asp:TextBox ID="textBoxSomeBody" runat="server"></asp:TextBox>
                                </td>
                            </tr>
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                    <div>
                        <asp:Label Width="100%" Style="text-align: justify;" ID="label6" runat="server" Text="Click the button below to view the Word document generated by Essential DocIO. 
                            Please note that MS Word Viewer or MS Word is required to view the resultant document."></asp:Label>
                    </div>
                    <br />
                    <div>
                        <table width="100%">
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                            
                            <tr>
                                <td align="left">
                                    <asp:CheckBox Style="margin-left: 3px" ID="checkBoxDefault" runat="server" AutoPostBack="True"
                                        Text=" Use Default Values" OnCheckedChanged="checkBoxDefault_CheckedChanged" />
                                </td>
                            </tr>
                            <tr>
                                <td height="5px">
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    <asp:Label Style="margin-left: 5px" Width="65px" runat="server" ID="label2" Text=" Save As :"></asp:Label>
                                    <asp:RadioButton ID="rdButtonWord97To2003" runat="server" GroupName="Group1" Text="Word 97-2003"/>
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2007" runat="server" GroupName="Group1"
                                        Text="Word 2007" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2010" runat="server" GroupName="Group1"
                                        Text="Word 2010" />
                                   <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2013" runat="server" GroupName="Group1"
                                            Text="Word 2013" Checked="True" />
                                   <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWordML" runat="server" GroupName="Group1"
                                            Text="WordML" />
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    <asp:Button Width="200px" Style="margin-right: 3px" ID="Button1" Height="27px" runat="server"
                                        OnClick="Button1_Click" Text="Generate Document" />
                                </td>
                            </tr>
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
