<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeBehind="Letter.aspx.cs" Inherits="WebSampleBrowser.DocIO.Letter" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    This sample illustrates generation of a letter using mail merge functionality of Essential DocIO with a pre-formatted document template.
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>
                    <div>
                        <asp:Label Width="100%" Style="text-align: justify;" ID="label6" runat="server" Text="Click the button below to view the Word document generated by Essential DocIO. 
                            Please note that MS Word Viewer or MS Word is required to view the resultant document."></asp:Label>
                    </div>
                    <br />
                    <b>Select any row from the grid below</b><div>
                        <br style="line-height: 10px" />
                    </div>
                    <div style="border: solid 1px #788DB3; padding: 5px 3px 5px 7px; background-color: #DEECFF;">
                        <asp:GridView Width="700px" BorderColor="#DAE5FF" AllowPaging="true" BorderStyle="Solid"
                            AutoGenerateSelectButton="true" runat="server" ID="gridView1" OnPageIndexChanged="gridView1_PageIndexChanged"
                            OnPageIndexChanging="gridView1_PageIndexChanging" OnSelectedIndexChanged="gridView1_SelectedIndexChanged">
                            <HeaderStyle BackColor="LightSteelBlue" BorderColor="#DAE5FF" BorderStyle="Solid" />
                        </asp:GridView>
                    </div>
                    <br />
                    <div>
                        <table width="100%">
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="left">
                                    <asp:CheckBox Checked="true" runat="server" ID="checkBoxChoose" Text=" Map DataFields"
                                        ToolTip="Map fields for merging that are not same as the Column Name in the data source" />
                                </td>
                                <td valign="middle" align="left">
                                    <asp:Label Width="65px" runat="server" ID="label1" Text="Save As :"></asp:Label>
                                    <asp:RadioButton ID="rdButtonWord97To2003" runat="server" GroupName="Group1" Text="Word 97-2003" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2007" runat="server" GroupName="Group1"
                                        Text="Word 2007" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2010" runat="server" GroupName="Group1"
                                        Text="Word 2010" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2013" runat="server" GroupName="Group1"
                                        Text="Word 2013" Checked="True" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWordML" runat="server" GroupName="Group1"
                                        Text="WordML" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td valign="middle" align="right">
                                    <asp:Button Width="200px" ID="Button1" Height="27px" runat="server" OnClick="Button1_Click"
                                        Text="Generate Document" />
                                </td>
                            </tr>
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                </td>
                <td>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>