<%@ Page MasterPageFile="~/samplebrowser.master" Language="C#" AutoEventWireup="true" CodeBehind="TableInsertion.aspx.cs" Inherits="WebSampleBrowser.DocIO.TableInsertion" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ControlsSection" runat="server">
    This samples illustrates inserting table in Word document using Essential DocIO. In this sample, a report is generated based on the records available in the Northwind database through ADO.Net connectivity.
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>
                    <div>
                        <asp:Label Width="100%" Style="text-align: justify;" ID="label6" runat="server" Text="Click the button below to view the Word document generated by Essential DocIO. 
                            Please note that MS Word Viewer or MS Word is required to view the resultant document."></asp:Label>
                    </div>
                    <br />
                    <div>
                        <table width="100%">
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="left">
                                    <asp:Label Width="65px" runat="server" ID="label1" Text="Save As :"></asp:Label>
                                    <asp:RadioButton ID="rdButtonWord97To2003" runat="server" GroupName="Group1" Text="Word 97-2003" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2007" runat="server" GroupName="Group1"
                                        Text="Word 2007" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2010" runat="server" GroupName="Group1"
                                        Text="Word 2010" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2013" runat="server" GroupName="Group1"
                                        Text="Word 2013" Checked="True" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWordML" runat="server" GroupName="Group1"
                                        Text="WordML" />
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    <asp:Button Width="200px" ID="Button1" Height="27px" runat="server" OnClick="Button1_Click"
                                        Text="Generate Document" />
                                </td>
                            </tr>
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
