#region Copyright Syncfusion Inc. 2001-2021.
// Copyright Syncfusion Inc. 2001-2021. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSampleBrowser.Toolbar {
    
    
    public partial class InlineToolbar {
        
        /// <summary>
        /// Inlinetoolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.Toolbar Inlinetoolbar;
        
        /// <summary>
        /// Cut control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Cut;
        
        /// <summary>
        /// Copy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Copy;
        
        /// <summary>
        /// Paste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Paste;
        
        /// <summary>
        /// Edit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Edit;
        
        /// <summary>
        /// Save control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Save;
        
        /// <summary>
        /// Bold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Bold;
        
        /// <summary>
        /// Underline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Underline;
        
        /// <summary>
        /// Strikethrough control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Strikethrough;
        
        /// <summary>
        /// left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem left;
        
        /// <summary>
        /// center control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem center;
        
        /// <summary>
        /// right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem right;
        
        /// <summary>
        /// justify control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem justify;
        
        /// <summary>
        /// Reload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Reload;
        
        /// <summary>
        /// Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Delete;
        
        /// <summary>
        /// Print control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Print;
        
        /// <summary>
        /// Export control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Syncfusion.JavaScript.Web.ToolbarItem Export;
    }
}
