<?xml version="1.0" encoding="utf-8"?><Database Name="DiagramData" Class="DiagramDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\DiagramData.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DiagramDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HierarchicalData" Member="HierarchicalDatas">
    <Type Name="HierarchicalData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HierarchicalDetails" Member="HierarchicalDetails">
    <Type Name="HierarchicalDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SourceNode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TargetNode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SourcePointX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TargetPointX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SourcePointY" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TargetPointY" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>